from author import *
add('cluster-internals','cka','Control plane internals and the Hard Way lens','Cluster lifecycle','Learn what each component needs before relying on an installer.',
'''A working cluster depends on identities, certificates, API connectivity, persistent state, scheduling, node execution, network routing and DNS. kubeadm and managed services automate parts of that work; understanding the parts makes failures diagnosable.

etcd stores Kubernetes API state. The API server is the normal entry point for that state. Controllers reconcile resources and the scheduler assigns unscheduled Pods. A kubelet manages the Pods assigned to its node through a container runtime interface.''',
'''Kubernetes the Hard Way is valuable because it exposes trust and bootstrap dependencies. Study how certificate subjects, SANs, kubeconfig endpoints and component flags connect. An otherwise valid certificate for the wrong endpoint still fails hostname verification; a trusted identity still needs authorization.

A small cluster may colocate several components on one machine. That does not make them one process or one failure mode. In a stacked etcd topology, losing a control-plane machine can affect both API serving and datastore membership. Draw failure domains separately from software responsibilities before claiming redundancy.''',
'For the proposed banking platform, distinguish an unavailable API endpoint from unavailable banking traffic. Existing Pods may still answer requests while new scheduling and configuration changes fail.',
[('Trust and API','Certificates, identity and accepted state'),('Control loops','Controller and scheduler decisions'),('Node execution','kubelet, runtime and Pod network')],
'On the disposable kind cluster, list kube-system Pods and inspect the node container’s /etc/kubernetes/manifests directory with a read-only docker exec. Map each static manifest to a responsibility. Compare the map with the Hard Way repository; do not run its bootstrap commands against this cluster.',
'Produce a dependency map showing which components talk to the API, which persist state and which execute workloads. Label colocated components and independent failure domains.',
'An operator restarts every worker because kubectl cannot reach the API. Propose a control-plane connectivity investigation first.',
('Do all Kubernetes components write directly to etcd?','No. Components normally coordinate through the Kubernetes API. Direct datastore access is restricted to the control-plane design.'),['concepts/overview/components/','https://github.com/kelseyhightower/kubernetes-the-hard-way','concepts/architecture/control-plane-node-communication/'],kind='architecture',code='kubectl -n kube-system get pods -o wide\ndocker exec techknowen-course-control-plane ls /etc/kubernetes/manifests\nkubectl get --raw="/readyz?verbose"')
add('kubeadm','cka','Build a kubeadm cluster with an explicit runbook','Cluster lifecycle','Prepare Linux machines, bootstrap trust, install networking and verify nodes.',
'''kubeadm bootstraps a Kubernetes control plane and joins nodes; it does not provision virtual machines or choose every network and runtime detail for you. Start with disposable Linux VMs, stable connectivity, correct time, unique identities and the prerequisites required by your selected Kubernetes version.

Install a compatible runtime and Kubernetes packages from the official version-specific repositories. Match the chosen runtime cgroup configuration with kubelet guidance. Decide the Pod network before init; overlapping Pod, Service and host network ranges cause difficult failures.''',
'''kubeadm init generates configuration and certificates and starts static control-plane Pods. A kubeconfig grants administrative access. A join command carries bootstrap information; treat real tokens and admin kubeconfig as sensitive. The node may remain NotReady until the chosen CNI is correctly installed.

Use a configuration file for repeatability, record the exact package versions and retain a sanitized command log. kubeadm reset is destructive to the node’s Kubernetes configuration and is not a general repair command. It also does not magically undo all network or external-storage changes. Learn cleanup on disposable machines only.''',
'Build one control-plane VM and two worker VMs for a banking test platform. This introduces genuine node placement choices that a single-node kind cluster cannot demonstrate.',
[('Prepare VMs','Runtime, time, connectivity and packages'),('Bootstrap','kubeadm init and controlled node join'),('Verify','CNI, Ready nodes, DNS and a workload')],
'Follow the linked installation and create-cluster guides for your pinned version on three disposable Linux VMs. Use admin/kubeadm-config.yaml in the manifest library as a starting point; review every network range and runtime path. Write down CIDRs and runtime socket before init. Install one compatible CNI using its official guide, join workers, then run the bank starter and a DNS test.',
'All nodes are Ready; system components are healthy; Pods on different nodes communicate; Service DNS and the application response work. Include package versions and sanitized init configuration.',
'Workers join but remain NotReady. Inspect kubelet Events and CNI installation instead of repeatedly regenerating join tokens.',
('Does kubeadm provision your VM network and install a chosen CNI automatically?','No. Infrastructure and the selected Pod network implementation must be prepared and installed as part of the runbook.'),['setup/production-environment/tools/kubeadm/install-kubeadm/','setup/production-environment/tools/kubeadm/create-cluster-kubeadm/','setup/production-environment/container-runtimes/'],mode='Disposable Linux VM lab',code='sudo kubeadm config images list\nsudo kubeadm init --config kubeadm-config.yaml\n# Use the generated, reviewed join command only on your lab workers.\nkubectl get nodes -o wide\nkubectl -n kube-system get pods -o wide',prereq='Three disposable Linux VMs; official version-matched package/runtime instructions; a reviewed kubeadm-config.yaml and CNI plan. Commands are runbook steps, not a complete installer.')
add('availability','cka','High availability, quorum and failure domains','Cluster lifecycle','More replicas help only when failures and dependencies are understood.',
'''A highly available control plane needs redundant API serving, an endpoint that can reach healthy API servers and a datastore design that tolerates intended failures. etcd uses quorum: a three-member cluster needs two members to agree; losing two removes its ability to make progress.

Control-plane redundancy does not ensure application availability. Workloads, ingress, DNS, storage and external services need their own failure-domain design. Three replicas on one node do not survive that node’s failure.''',
'''Adding an even-numbered etcd member does not always improve failure tolerance. A four-member cluster needs three votes and still tolerates only one member loss. Quorum protects consistency by refusing progress without enough agreement; forcing independent writes during a partition would undermine that property.

A load balancer for the API is itself a dependency. Certificates must cover the chosen endpoint. In a stacked topology, each control-plane loss can remove an etcd member too; external etcd separates roles at additional operational cost. Design for the failures you can test and afford, not merely a larger diagram.''',
'The bank platform’s design proposes three control-plane nodes across failure domains and application replicas distributed across workers, with independent storage recovery evidence.',
[('API availability','Healthy servers behind a stable endpoint'),('etcd quorum','Two of three members agree'),('Application availability','Spread replicas and protect dependencies')],
'Create a failure table for one, two and three members lost from a three-member datastore. Separately remove a worker in a disposable multi-node lab and observe application placement. Keep datastore failure injection in an isolated admin lab with a tested recovery plan.',
'Your table correctly distinguishes consistency-preserving unavailability from data loss. Your application test records actual available replicas and request success during a node event.',
'A proposal calls four etcd nodes twice as resilient as two. Calculate majority requirements and compare three versus four.',
('How many member failures can a healthy three-member etcd cluster tolerate while maintaining quorum?','One, provided the remaining two can communicate and are healthy.'),['setup/production-environment/tools/kubeadm/ha-topology/','setup/production-environment/tools/kubeadm/high-availability/','https://etcd.io/docs/v3.6/faq/'],mode='Architecture exercise / optional VM lab',kind='architecture')
add('upgrades','cka','Upgrade without ignoring compatibility','Cluster lifecycle','Plan versions, backups, node disruption and verification together.',
'''An upgrade is a controlled change to interacting components. Review supported version skew, deprecated APIs, runtime/CNI/CSI compatibility and backup readiness. kubeadm upgrades follow a documented order; skipping minor versions is unsupported in the standard kubeadm upgrade path.

Upgrade the control plane, then additional control-plane nodes and workers following the version-specific procedure. Drain workloads at the instructed point, upgrade packages, restart services and uncordon after verification.''',
'''A healthy API is only one success condition. Admission webhooks, DNS, storage provisioning, ingress and workload rollouts must also work. A PodDisruptionBudget can block voluntary eviction if the workload cannot tolerate the drain. That is useful evidence of insufficient spare capacity, not a reason to force deletion immediately.

The newest online documentation may describe a different source/target version than your lab. Select the archived documentation for your actual transition. Package repositories and exact version strings vary by distribution; resolve and pin them rather than copying an old apt command from a blog.''',
'Upgrade the isolated bank admin lab one supported minor step. Keep the information service under repeated requests and record disruption and recovery times as observations.',
[('Plan','Compatibility and tested recovery'),('Change one node','Upgrade, drain and restart as documented'),('Verify and return','Node health and application behaviour')],
'In the VM lab, inventory versions and run kubeadm upgrade plan. Follow the exact version-transition guide for package and control-plane changes. Upgrade one worker at a time and verify the bank request path after each.',
'All component versions are within supported skew; nodes return Ready; DNS, Service access, storage and rollouts pass. Record any observed interruption.',
'Drain is blocked by a budget. Inspect allowed disruptions and replica health; add justified capacity or repair replicas before deciding whether a disruption exception is acceptable.',
('Is a successful control-plane upgrade sufficient evidence that workloads are healthy?','No. Test the dependent components and application paths after the infrastructure change.'),['tasks/administer-cluster/kubeadm/kubeadm-upgrade/','https://kubernetes.io/releases/version-skew-policy/','tasks/administer-cluster/safely-drain-node/'],mode='Disposable Linux VM lab',code='kubectl get nodes -o wide\nsudo kubeadm upgrade plan\n# Continue with the official guide for YOUR source and target versions.\n# Replace LAB_WORKER with a verified disposable worker name.\nkubectl drain LAB_WORKER --ignore-daemonsets\nkubectl uncordon LAB_WORKER',prereq='A disposable kubeadm VM cluster, a tested backup/restore path and the version-specific upgrade guide. Do not use kind node containers as a substitute for this exercise.')
add('etcd-recovery','cka','Back up and restore control-plane state','Cluster lifecycle','A snapshot is useful only when a restoration is understood and tested.',
'''etcd stores Kubernetes API state, including sensitive data depending on encryption configuration. Protect snapshots like the cluster’s data and credentials. Use the tool versions and endpoint/TLS settings appropriate to the cluster.

An etcd snapshot does not back up application data on persistent volumes or in external databases. Recovering Kubernetes objects without their corresponding data can leave a superficially restored but unusable service.''',
'''etcdctl snapshot save and etcdutl snapshot restore have different roles. Restoration builds a new data directory; it is not a harmless overwrite of a running datastore. Kubernetes watches and caches require careful revision handling after a restore; follow current etcd disaster-recovery guidance, including revision bump and compaction marking where recommended.

The recovery runbook must cover member identity, endpoints, certificates, manifests, data-directory ownership and restart order. Test in an isolated environment and verify both API objects and application dependencies. Document an observed recovery duration; an untested estimate is not an achieved RTO.''',
'The bank recovery plan separates cluster configuration, image availability, the fictional page content and any future external ledger data. Each has a restore owner and verification test.',
[('Snapshot','Capture and protect API state'),('Restore isolated state','Correct tools, identity and revision handling'),('Verify dependencies','Objects plus actual application data')],
'On a disposable VM cluster, follow the official etcd/Kubernetes backup guide using the cluster’s actual endpoint and certificate paths. Restore into an isolated replacement environment rather than experimenting on a live directory. Record a restore of a known ConfigMap and a working application request.',
'The restored object matches the checkpoint, the API is healthy and the application works. Explicitly list data not included in the etcd snapshot.',
'A restored Deployment references a missing registry image or missing volume data. Explain why an etcd snapshot alone cannot satisfy recovery.',
('Does an etcd snapshot include the files on every PersistentVolume?','No. It contains Kubernetes datastore state, not all application storage contents.'),['tasks/administer-cluster/configure-upgrade-etcd/','https://etcd.io/docs/v3.6/op-guide/recovery/'],mode='Disposable Linux VM lab',code='etcdctl version\netcdutl version\n# Use the actual lab endpoint and TLS files from its reviewed runbook.\n# Snapshot example; placeholders must be replaced before execution:\netcdctl --endpoints=https://127.0.0.1:2379 --cacert=LAB_CA --cert=LAB_CLIENT_CERT --key=LAB_CLIENT_KEY snapshot save lab-snapshot.db\netcdutl snapshot status lab-snapshot.db --write-out=table',prereq='Disposable etcd/kubeadm VM environment; trusted TLS paths; current recovery documentation. Restore is intentionally a reviewed runbook, not a one-line production command.')
add('extension-interfaces','cka','CRI, CNI, CSI and Operators','Cluster lifecycle','Separate execution, network and storage extension contracts.',
'''CRI connects kubelet with the container runtime. CNI provides container network configuration through an implementation. CSI connects Kubernetes storage operations with storage drivers. These interfaces solve different problems; installing one does not replace the others.

Operators add domain-specific reconciliation through custom APIs and controllers. They can depend on these lower layers and introduce further permissions, webhooks and lifecycle requirements.''',
'''A sandbox creation failure can come from runtime or network setup before the application ever starts. A volume attachment failure can block startup even while the image is already present. Use the failing operation and relevant component logs to choose a boundary to investigate.

An extension’s version compatibility, privileges and upgrade behaviour belong in cluster lifecycle planning. Helm and Kustomize package/render deployment configuration; they do not guarantee an extension is correct for your Kubernetes version. Inspect CRDs, permissions, Pods and actual network/storage results after installing a component.''',
'bank-web needs execution and networking; the persistent marker lab additionally needs a storage provisioner. The BankReport CRD adds a schema but still needs a controller for real reports.',
[('CRI','Run the container sandbox and process'),('CNI','Configure Pod network connectivity'),('CSI','Provision, attach and mount storage')],
'Inventory the runtime from node status, the networking DaemonSet/configuration and available CSIDrivers/StorageClasses. Explain the local kind provisioner’s limits. Inspect the report CRD and identify the missing application controller.',
'Your inventory names implementations, versions where available, owners and a concrete validation test for each extension boundary.',
'A Pod cannot mount a volume. Rebuilding its container image will not repair a CSI authentication or topology failure.',
('Does installing a CRD automatically implement its reconciliation behaviour?','No. A separate controller must reconcile the custom objects, with appropriate dependencies and permissions.'),['concepts/containers/cri/','concepts/extend-kubernetes/compute-storage-net/network-plugins/','concepts/storage/volumes/#csi','concepts/extend-kubernetes/operator/'],kind='architecture',code='kubectl get nodes -o custom-columns=NAME:.metadata.name,RUNTIME:.status.nodeInfo.containerRuntimeVersion\nkubectl -n kube-system get daemonsets\nkubectl get csidrivers,storageclasses\nkubectl get crds')
add('admin-rbac','cka','Administer access without accidental privilege','Cluster lifecycle','Review effective grants, cluster scope and escalation routes.',
'''Administrative RBAC includes both namespace-scoped work and cluster-scoped resources. A ClusterRoleBinding grants its role across the relevant cluster scope. A RoleBinding can grant a ClusterRole’s applicable permissions within one namespace.

Permission to create Pods can be powerful because workloads may mount resources or use identities available in that namespace. Access design must consider what a subject can cause indirectly, not just whether it can read one API object directly.''',
'''Review bind, escalate and impersonate permissions with particular care. Existing broad grants can undermine a narrow new role because authorization permissions are additive. A service account used by a controller should receive only the operations needed for its reconciliation tasks.

Separate administrative identities from application identities and record emergency access. Auditing can show API activity but requires a configured policy and retention. Never confuse an audit log of API requests with a complete application transaction audit.''',
'The banking support role reads Pods and logs but cannot alter RBAC or access Secrets. Platform administrators use a separate, time-bounded operational process.',
[('Subject','Human or workload identity'),('Bindings','Namespace and cluster grants'),('Effective access','Direct and indirect capabilities')],
'Extend the local bank-reader Role to allow reading pods/log, then verify it still cannot create rolebindings or read Secrets. Use auth can-i --list for the impersonated identity and explain each granted verb.',
'The access matrix contains allowed and denied operations with observed results. Record that impersonation itself was done using the lab administrator.',
'A narrow Role appears correct but the subject can still read Secrets. Search for another binding that grants the permission.',
('Can a narrow Role revoke a broader grant from another binding?','No. Standard RBAC grants are additive. Remove or correct the broader grant through the proper administrative process.'),['reference/access-authn-authz/rbac/','concepts/security/rbac-good-practices/','tasks/debug/debug-cluster/audit/'],code='kubectl auth can-i --list -n tk-bank --as=system:serviceaccount:tk-bank:bank-reader\nkubectl auth can-i create rolebindings -n tk-bank --as=system:serviceaccount:tk-bank:bank-reader\nkubectl get clusterrolebindings')
add('scheduling','cka','Scheduling, affinity, taints and spread','Workloads and scheduling','Separate permission to land from a preference or requirement to land.',
'''The scheduler filters unsuitable nodes and scores eligible choices. Requests, selectors, affinity, taints and storage topology can all affect placement. nodeSelector is an exact matching rule; node affinity offers required and preferred forms.

A toleration permits a Pod to tolerate a matching taint. It does not force the Pod onto that node. Use a positive placement rule when placement is required. A preferred rule may be ignored when it cannot be satisfied; a required rule can leave the Pod Pending.''',
'''Pod affinity and anti-affinity reason about other Pods and topology domains rather than only node labels. Topology spread constraints balance matching workloads across eligible domains with specified skew and unsatisfiable behaviour. Label quality is part of correctness: a missing or misleading zone label invalidates the intended resilience model.

Binding a Pod with nodeName bypasses the normal scheduler choice and can defeat the reasoning behind scheduling policies. Do not use it as a general remedy for Pending. Read scheduler Events and calculate whether a valid placement actually exists.''',
'Bank replicas should survive one worker loss. A preferred spread improves ordinary placement, while a required anti-affinity rule may need enough nodes to keep every replica schedulable.',
[('Eligibility','Resources, taints and required rules'),('Preference','Score eligible nodes'),('Distribution','Spread across labelled failure domains')],
'On a multi-node disposable cluster, label two workers with fictional zones. Deploy three tiny replicas using a topology spread constraint, inspect placement, then remove one eligible zone label in the lab and observe the outcome. Restore it afterward.',
'The observed placement matches the declared rule and available topology. Record Pending Events when no legal placement exists rather than calling the scheduler random.',
'A Pod tolerates dedicated=bank:NoSchedule but lands elsewhere. Add the required affinity if dedicated placement is truly intended.',
('Does a toleration attract a Pod to a tainted node?','No. It removes that taint’s scheduling obstacle; selection or affinity determines positive placement intent.'),['concepts/scheduling-eviction/assign-pod-node/','concepts/scheduling-eviction/taint-and-toleration/','concepts/scheduling-eviction/topology-spread-constraints/'],code='kubectl get nodes --show-labels\nkubectl explain pod.spec.topologySpreadConstraints\nkubectl -n tk-bank get pods -o wide\nkubectl -n tk-bank get events --sort-by=.metadata.creationTimestamp',prereq='A disposable multi-node lab for placement experiments; the single-node course cluster supports only inspection.')
add('autoscaling','cka','HPA, metrics and node capacity','Workloads and scheduling','Scaling replicas and supplying machines are separate feedback loops.',
'''Horizontal Pod Autoscaler adjusts replica count from observed metrics and a target. CPU utilization targets depend on requests: without meaningful requests and a working metrics pipeline, the decision can be missing or misleading.

Node autoscaling changes available cluster capacity. More desired Pods do not guarantee they can be scheduled. Application bottlenecks such as a database connection pool can also prevent extra replicas from improving throughput.''',
'''The basic proportional intuition is desired replicas approximately equal current replicas multiplied by observed metric divided by target. Real behaviour also includes missing metrics, readiness, tolerance, stabilization and scaling policies. A brief spike should not be interpreted as an obligation to change replicas instantly.

HPA and manual replica settings can conflict if both keep overwriting the same desired count. Vertical changes to resource requests can alter CPU utilization ratios. Coordinate scaling ownership and test startup, load, cooldown and maximum capacity with a bounded load generator.''',
'If four bank replicas average 80% utilization against a 50% target, a simple ratio suggests about seven replicas after rounding up, before the controller’s additional rules and limits.',
[('Measure','Resource metrics plus requests'),('Replica controller','Target, bounds and stabilization'),('Capacity','Nodes and downstream dependencies')],
'First check whether metrics.k8s.io is available. In a metrics-enabled disposable cluster, create an autoscaler for a CPU-busy test workload with explicit requests; apply a bounded load and watch replicas. Do not disable production TLS controls just to make a local metrics install work.',
'Record observed metrics, HPA conditions, desired/current replicas and scheduling. Explain any interval where desired replicas exceed running replicas.',
'HPA shows unknown CPU. Inspect metrics API, Pod requests and HPA conditions before increasing maxReplicas.',
('Can HPA create new physical or virtual worker nodes by itself?','No. HPA changes workload replicas. Node autoscaling is a separate capacity mechanism.'),['tasks/run-application/horizontal-pod-autoscale/','concepts/workloads/autoscaling/horizontal-pod-autoscale/','tasks/debug/debug-cluster/resource-metrics-pipeline/'],code='kubectl get apiservice v1beta1.metrics.k8s.io\nkubectl top nodes\nkubectl -n tk-bank top pods\n# Only after a working metrics pipeline and suitable requests:\nkubectl -n tk-bank autoscale deployment bank-web --cpu-percent=60 --min=2 --max=5\nkubectl -n tk-bank describe hpa bank-web',prereq='A metrics-enabled disposable cluster; the basic kind setup does not install metrics-server automatically.')
add('disruptions','cka','Drains, disruption budgets and graceful shutdown','Workloads and scheduling','Plan voluntary maintenance without confusing it with failure immunity.',
'''Cordon prevents ordinary new scheduling to a node. Drain evicts eligible workloads so the node can be maintained. A PodDisruptionBudget constrains voluntary disruptions through the eviction API; it is not a shield against a machine crash or every deletion mechanism.

A budget can allow zero disruptions when too few replicas are healthy. Maintenance then needs restored health or additional capacity. Forcing through the budget changes the availability decision and should be explicit.''',
'''DaemonSet and static Pods are handled differently from ordinary controller-managed workloads during drain. Local ephemeral data may be lost when a Pod is removed. The flags that ignore agents or permit emptyDir loss are operational choices, not harmless boilerplate.

Graceful termination needs cooperation from the application, endpoint updates and traffic draining. A long termination grace period does not guarantee that all requests finish; the process must handle signals and stop accepting new work. Measure what clients actually experience.''',
'Two healthy bank replicas with minAvailable: 1 can normally tolerate one voluntary eviction, assuming another node can host replacement work. A single-node lab cannot demonstrate node-level continuity.',
[('Cordon','Stop normal new placement'),('Eviction decision','Budget and local-data checks'),('Replacement + recovery','Ready capacity on another node')],
'On a disposable multi-node lab, create a PDB for bank-web and drain one worker while sending repeated requests. Record allowedDisruptions before and during maintenance, then uncordon the node.',
'You can show where traffic remained available or failed and why. A successful drain alone is not proof of zero disruption.',
'A one-replica service uses minAvailable: 1, so drain blocks. Explain the availability requirement and capacity trade-off before choosing a remedy.',
('Does a PDB prevent a node from unexpectedly failing?','No. It controls certain voluntary disruptions; redundancy and recovery design address involuntary failures.'),['concepts/workloads/pods/disruptions/','tasks/administer-cluster/safely-drain-node/'],code='kubectl -n tk-bank create poddisruptionbudget bank-web --selector=app=bank-web --min-available=1\nkubectl -n tk-bank get pdb bank-web\n# Drain only a verified worker in the separate multi-node lab.\nkubectl drain LAB_WORKER --ignore-daemonsets\nkubectl uncordon LAB_WORKER',prereq='Disposable multi-node cluster, healthy replicas and an understood local-data policy.')
add('cni-dataplane','cka','Pod networking, Service forwarding and eBPF','Services and networking','Follow packets through implemented networking rather than through API boxes.',
'''Pods need addresses, routes and a way to communicate across nodes. The network implementation may route directly or encapsulate packets; the details depend on the CNI and infrastructure. Service forwarding maps a stable virtual address to usable backends.

The API stores desired objects and endpoint information, while node-side agents program the data path. Customer HTTP traffic does not normally pass through the Kubernetes API server on its way to a web Pod.''',
'''iptables, IPVS and eBPF are implementation mechanisms with different operational tools and trade-offs. Do not diagnose an eBPF-based Service implementation by assuming every Service must have identical iptables chains. Read the implementation’s observability and policy guidance.

MTU mismatch, routing overlap, source NAT, conntrack pressure and blocked node-to-node ports can cause symptoms that application logs do not explain. Start with one source, one destination, one port and a timestamp. Compare same-node versus cross-node and Pod-IP versus Service-IP paths to narrow the failing boundary.''',
'If bank-web responds by Pod IP on the same node but cross-node Service access fails, separate overlay/routing health from Service selection before changing the Deployment.',
[('Source Pod','Network namespace and route'),('Node data plane','CNI path and Service translation'),('Destination Pod','Target process and response route')],
'In a multi-node lab, place a diagnostic client away from a bank-web backend. Test DNS, direct Pod address and Service address independently. Record node placement and the CNI implementation.',
'Produce a four-cell result matrix: same/cross node versus Pod/Service address. Use it to explain the smallest suspected failing layer.',
'An application works on one node but fails across nodes. Check routes, MTU and network-agent status before assuming every backend has bad code.',
('Does the Service API object itself forward every application packet?','No. The configured data-plane implementation programs forwarding based on API state.'),['concepts/cluster-administration/networking/','concepts/services-networking/service/','concepts/extend-kubernetes/compute-storage-net/network-plugins/'],kind='architecture',code='kubectl -n tk-bank get pods -o wide\nkubectl -n tk-bank get service bank-web -o wide\nkubectl -n tk-bank get endpointslices -l kubernetes.io/service-name=bank-web\nkubectl -n kube-system get pods -o wide',prereq='Service/DNS fundamentals; a multi-node lab for cross-node experiments.')
add('coredns','cka','CoreDNS and systematic name-resolution diagnosis','Services and networking','Check the client, DNS service and upstream resolution separately.',
'''A Pod’s resolver configuration determines which DNS server and search suffixes it uses. Cluster DNS normally supplies Service names and forwards other names according to its configuration. A successful external lookup does not prove that the expected internal namespace name exists.

Check the exact query, namespace, resolver configuration and DNS response before modifying CoreDNS. A denied DNS packet and an NXDOMAIN reply indicate different failures.''',
'''DNS can use both UDP and TCP; policies or firewalls that allow only one may fail for some responses. Search suffix expansion and ndots can produce more queries than the short name suggests. Caching can retain an old answer temporarily, so timing matters.

CoreDNS itself depends on scheduling, its Service endpoints, API access for service discovery and upstream reachability where forwarding is required. A broad Corefile edit affects many workloads. Validate syntax and change one condition in a disposable environment before proposing a cluster-wide fix.''',
'From a client in another namespace, bank-web alone may query the wrong namespace. bank-web.tk-bank identifies the intended Service within a typical cluster search configuration.',
[('Client resolver','Query and search suffixes'),('Cluster DNS','Service discovery and cache'),('Upstream DNS','External names when forwarded')],
'Run a busybox diagnostic Pod and compare nslookup bank-web.tk-bank with an intentionally misspelled Service name. Inspect /etc/resolv.conf. Check CoreDNS Pods, its Service and logs using read-only commands.',
'You distinguish a valid answer, NXDOMAIN and timeout, and identify which evidence supports each diagnosis.',
'A default-deny policy blocks DNS. Restore the specific resolver access instead of replacing working Service names with hard-coded IPs.',
('Does a DNS timeout mean the requested Service name does not exist?','Not necessarily. The request or response may be blocked, or the DNS service may be unavailable. NXDOMAIN is a different result.'),['tasks/administer-cluster/dns-debugging-resolution/','tasks/administer-cluster/coredns/','concepts/services-networking/dns-pod-service/'],code='kubectl -n tk-bank run dns-check --image=busybox:1.37 --restart=Never -- sh -c "cat /etc/resolv.conf; nslookup bank-web.tk-bank"\nkubectl -n tk-bank logs dns-check\nkubectl -n kube-system get service kube-dns\nkubectl -n kube-system logs deployment/coredns --tail=30\nkubectl -n tk-bank delete pod dns-check')
add('gateway-api','cka','Gateway API and delegated routing','Services and networking','Separate infrastructure ownership from application route ownership.',
'''GatewayClass identifies a controller/implementation class. A Gateway configures listeners and infrastructure intent. HTTPRoute expresses application routing rules attached to an allowed parent. This division lets platform and application teams hold different responsibilities.

Gateway API resources are CRDs, not automatically present on every cluster. Install a compatible implementation and the appropriate CRDs using its official guidance. An accepted HTTPRoute is not the same as a programmed, reachable external endpoint.''',
'''Route status conditions such as Accepted and ResolvedRefs help explain whether the parent accepted the route and whether references are valid. A cross-namespace backend reference can require a ReferenceGrant in the target namespace. That grant is distinct from listener allowedRoutes rules governing route attachment.

Hostnames, listener ports, TLS settings, path rules and backend health all contribute to traffic success. Weighted backends allow more explicit canary intent than changing replica ratios, but observed traffic can still depend on connection patterns. Record status and exercise actual requests.''',
'The platform team owns a bank-public Gateway. The application team attaches an information-page HTTPRoute whose backend is bank-web; a future cross-namespace backend needs an explicit trust decision.',
[('GatewayClass / Gateway','Implementation and listener ownership'),('HTTPRoute','Allowed attachment and routing rules'),('Backend + grants','Service reference and trust boundaries')],
'Open admin/gateway.yaml in the manifest library, replace its class with a real installed GatewayClass, and save the file. In a Gateway-enabled lab, apply that Gateway and HTTPRoute using the chosen controller’s supported class. Inspect parent status conditions and test the hostname/path. Change the backend name to a missing Service and observe ResolvedRefs before restoring it.',
'The Gateway is programmed, route references resolve and the client receives the intended page. If no implementation is installed, mark runtime routing as not tested.',
'A cross-namespace reference fails despite a matching hostname. Inspect ReferenceGrant and allowedRoutes as separate controls.',
('What does ReferenceGrant control?','It permits specified cross-namespace references to resources in the namespace that owns the grant; it is not a general network allow rule.'),['concepts/services-networking/gateway/','https://gateway-api.sigs.k8s.io/guides/','https://gateway-api.sigs.k8s.io/reference/api-types/referencegrant/'],kind='architecture',mode='Gateway-capable cluster',code='kubectl get gatewayclasses\nkubectl apply -f gateway.yaml\nkubectl get gateways,httproutes -A\nkubectl explain httproute.spec.parentRefs\nkubectl describe httproute bank-info -n tk-bank',prereq='Gateway API CRDs and a compatible controller; use its version-matched installation and example configuration.')
add('csi-storage','cka','Administer storage lifecycle and topology','Storage','Provisioning, attachment, mounting and recovery are separate operations.',
'''A StorageClass defines provisioning behaviour and parameters for its storage implementation. The PVC requests capacity; the PV records provisioned or supplied storage. A Pod can be blocked while storage is unbound, unattached or unmounted, and those stages need different evidence.

Reclaim policy governs what happens to backing storage after claim release. Retain preserves a resource for manual handling; Delete can remove it through the provisioner. Neither is a substitute for a tested backup policy.''',
'''Zonal storage constrains placement. WaitForFirstConsumer lets scheduling and volume topology be considered together. A volume cannot simply be moved across arbitrary zones because a Pod is rescheduled. CSI controller and node components coordinate provisioning, attachment and mount operations.

Expansion requires support from the StorageClass, driver, volume and filesystem path. A larger requested PVC does not prove the filesystem inside the running container expanded successfully. Snapshot API availability also does not guarantee application-consistent recovery; quiescing or database-aware backup may be needed.''',
'The bank marker exercise proves persistence across one Pod replacement. A platform storage acceptance test additionally checks topology, node replacement, reclaim behaviour and a restored data read.',
[('Provision','Class and capacity produce a volume'),('Attach and mount','Match node topology and access mode'),('Recover','Restore and verify application data')],
'Inspect the bound marker PVC, PV, StorageClass and consumer node. Build a retention table before any deletion. In a CSI-enabled lab, test a supported expansion and verify both API capacity and the mounted filesystem.',
'Your evidence identifies the driver, binding mode, reclaim policy and failure-stage messages. State clearly which recovery operations were not performed.',
'A Pod moves zones and cannot attach its disk. Investigate topology and storage design instead of force-deleting the PV.',
('Does a larger PVC capacity field alone prove an application sees a larger filesystem?','No. Verify the actual mounted filesystem and any driver/filesystem expansion conditions.'),['concepts/storage/storage-classes/','concepts/storage/persistent-volumes/','concepts/storage/volume-snapshots/'],code='kubectl -n tk-bank get pvc bank-learning-data -o yaml\nkubectl get pv\nkubectl get storageclass -o yaml\nkubectl get volumeattachments\nkubectl -n tk-bank describe pod bank-storage')
add('node-triage','cka','Diagnose an unhealthy node','Troubleshooting','Use conditions, kubelet/runtime evidence and resource pressure before restarting blindly.',
'''A node reports conditions such as Ready and resource pressure. NotReady is a symptom, not a root cause. The kubelet may be unable to reach the API, the runtime may be unhealthy, certificates may fail or the node may be under pressure.

Start with the node object and recent Events, then inspect the node’s own services in the VM lab. kubectl logs cannot retrieve every failure when the kubelet or node connection itself is broken.''',
'''Disk pressure can come from images, writable layers, logs or other node storage. Deleting application data is not a safe generic disk remedy. Establish which filesystem is full and what owns the growth. CPU starvation, memory pressure and PID exhaustion have different signatures.

Use journalctl for service history and crictl for CRI runtime inspection, configured for the correct socket. System time and certificate validity affect TLS. Keep the investigation read-only until a causal hypothesis is strong enough for one controlled change. A reboot may restore service while hiding the unresolved cause.''',
'A bank worker becomes NotReady while its existing application requests intermittently fail. Collect node conditions and kubelet/runtime evidence before deciding whether to drain, repair or replace it.',
[('Cluster evidence','Conditions, Events and placement'),('Node evidence','kubelet, runtime, disk and time'),('Controlled repair','Verify cause and restore readiness')],
'In the disposable Linux VM lab, deliberately stop kubelet on one worker, observe the delayed node condition change, then restore it. Compare that symptom with a read-only disk-pressure investigation. Do not inject faults into a shared cluster.',
'Your record identifies the injected cause, observation delay, affected workloads and the evidence that the node recovered.',
'A node is NotReady and an operator changes the banking image. Explain why workload code is unlikely to fix a stopped kubelet.',
('Why might kubectl logs be unavailable during node failure?','It relies on a working path to the node/container logs; failure of the kubelet, runtime or connectivity can block that path.'),['tasks/debug/debug-cluster/','tasks/debug/debug-cluster/crictl/','concepts/architecture/nodes/'],mode='Disposable Linux VM lab',code='kubectl describe node LAB_WORKER\n# On that disposable VM, inspect before changing anything:\nsudo systemctl status kubelet containerd\nsudo journalctl -u kubelet --since "15 minutes ago"\ndf -h\nsudo crictl info',prereq='Admin access to a disposable Linux worker VM, correct runtime socket and permission to conduct isolated failure experiments.')
add('control-plane-triage','cka','Diagnose API, static Pod and certificate failures','Troubleshooting','Locate the failed dependency when kubectl itself stops working.',
'''If the API is unavailable, first distinguish DNS/endpoint resolution, TCP reachability, TLS validation, authentication, authorization and server health. Each boundary produces different evidence. Do not replace credentials to solve a network timeout.

kubeadm commonly runs control-plane components as static Pods managed by kubelet. Their manifests live on the control-plane host. When the API is down, host-level runtime and service tools may be necessary.''',
'''An invalid manifest edit can stop an API server. Keep a known-good copy outside the watched manifest directory: backup files inside that directory can be interpreted as additional manifests. File paths, certificate mounts and listening addresses must match the actual host.

Certificate expiry, incorrect SANs and untrusted issuers are distinct TLS problems. kubeadm certs check-expiration is useful for kubeadm-managed certificates, but it does not inspect every external certificate in a platform. Renewal requires the correct ownership and component restart procedure. Track validity proactively rather than treating expiry as an unpredictable outage.''',
'The bank platform runbook includes a stable API endpoint, host access, a sanitized manifest checkpoint and a certificate inventory before any control-plane maintenance.',
[('Reach the API','Name, network and TLS checks'),('Inspect host components','Static manifests and runtime logs'),('Repair one dependency','Restore health and retest clients')],
'On the disposable VM control plane, inventory static manifests and certificate expiration. Practise recovering a deliberately malformed copied manifest only after recording a known-good version and an out-of-band access route.',
'The corrected control plane serves readyz, authenticated kubectl calls and subsequent workload changes. Record the exact failed field or certificate condition.',
'An administrator stores api-server.yaml.bak beside static manifests. Move backup material outside the watched directory and inspect the resulting duplicate/conflicting workload behaviour.',
('Where should a backup copy of a static Pod manifest be stored?','Outside the kubelet’s watched manifest directory so it cannot be mistaken for another active manifest.'),['tasks/administer-cluster/kubeadm/kubeadm-certs/','tasks/configure-pod-container/static-pod/','tasks/debug/debug-cluster/'],mode='Disposable Linux VM lab',code='sudo kubeadm certs check-expiration\nsudo ls /etc/kubernetes/manifests\nsudo crictl ps -a\nsudo journalctl -u kubelet --since "15 minutes ago"\nkubectl get --raw="/readyz?verbose"',prereq='Disposable kubeadm VM, host access and known-good backups. Do not edit a real control-plane manifest for practice.')
add('network-triage','cka','A networking fault tree you can actually use','Troubleshooting','Test names, endpoints, ports, policies and cross-node paths independently.',
'''Begin at the client and reproduce a specific request. Can the hostname resolve? Does the destination Service exist in the intended namespace? Does it select ready endpoints? Does the backend process listen on the target port? Each answer removes a class of causes.

Test the direct backend and Service path separately where permitted. A working Pod IP with a broken Service suggests selection or forwarding issues; a broken Pod IP can point to application listening, policy or network reachability.''',
'''A timeout and connection refusal imply different observations but are not universal diagnoses. A firewall can reject or drop; a proxy can generate an error on behalf of another component. Interpret the error with packet path and controller evidence rather than a memorised slogan.

NetworkPolicy checks need both source egress and destination ingress. External exposure adds load-balancer health checks, firewall rules, route attachment and TLS. Do not make a dozen simultaneous changes: change one suspected cause, repeat the original request, and retain the before/after evidence.''',
'bank-web is Ready but its Service has a typo in app selection. The fastest decisive evidence is an empty EndpointSlice set for that Service and a comparison of labels.',
[('Resolve and select','DNS, namespace and endpoints'),('Reach the listener','Port, policy and data plane'),('Check external layers','Gateway/Ingress, TLS and load balancer')],
'Patch only the bank Service selector to an incorrect value, record the endpoint state and a failed client request, then restore bank.yaml and repeat the same request. Run this only in the disposable course cluster.',
'Your root cause identifies the wrong selector and your recovery evidence includes a real successful response, not merely Ready Pods.',
'An external 503 is treated as a DNS failure. Explain what the HTTP response already proves and inspect backend health next.',
('What evidence most directly checks whether a Service selects usable backends?','Inspect its EndpointSlices, endpoint readiness and the corresponding Pod labels and ports.'),['tasks/debug/debug-application/debug-service/','tasks/administer-cluster/dns-debugging-resolution/','concepts/services-networking/network-policies/'],code='kubectl -n tk-bank get svc bank-web -o yaml\nkubectl -n tk-bank get pods --show-labels\nkubectl -n tk-bank get endpointslices -l kubernetes.io/service-name=bank-web\nkubectl -n tk-bank patch svc bank-web -p \'{"spec":{"selector":{"app":"bank-typo"}}}\'\n# Observe the fault, then restore:\nkubectl apply -f bank.yaml')
add('observability','cka','Metrics, logs, events, traces and audit','Troubleshooting','Choose evidence for the question instead of collecting noise.',
'''Metrics show measurements over time. Logs describe individual process events. Traces connect work across request boundaries. Kubernetes Events describe object-related observations, while audit logs record configured API activity. These are complementary signals.

A CPU graph does not explain every failed user request. An application log without timestamps, correlation or retention may be insufficient for incident reconstruction. Define the question first: saturation, error rate, restart cause, latency segment or unauthorized API change.''',
'''A useful service-level indicator measures user-relevant outcomes, such as valid information-page requests that succeed within a threshold. Infrastructure availability is only a proxy. Percentiles require meaningful sample volumes, and averages can hide slow tails.

Telemetry has cost and privacy implications. Do not log dummy patterns in a way that encourages logging real tokens, account numbers or payloads later. Control cardinality, retention and access. Monitoring should test its own gaps: a missing metric series is different from zero failures.''',
'For the bank page, compare request success with Pod readiness, restart count and node resource usage. A green node dashboard does not prove the page content is correct.',
[('User outcome','Success, latency and correctness'),('System signals','Metrics, logs, traces and Events'),('Decision','Diagnose, alert or verify a change')],
'Create a short evidence timeline for a failed rollout: timestamps, desired image, Events, ready replica count and HTTP result. Where metrics are unavailable, explicitly mark that signal absent instead of inventing utilization.',
'The timeline supports a causal explanation and separates observed facts from hypotheses. No sensitive values appear in the evidence.',
'No errors are logged because the logger is broken. Add an independent request probe and monitor telemetry health.',
('Is the absence of error logs proof that the service is healthy?','No. Traffic or telemetry may be missing. Correlate independent user-level checks and signal health.'),['concepts/cluster-administration/observability/','concepts/cluster-administration/logging/','tasks/debug/debug-cluster/resource-metrics-pipeline/'],code='kubectl -n tk-bank get events --sort-by=.metadata.creationTimestamp\nkubectl -n tk-bank logs deployment/bank-web --timestamps --tail=40\nkubectl -n tk-bank get pods -o wide\n# top requires a working metrics API:\nkubectl -n tk-bank top pods')
add('cka-capstone','cka','CKA incident room and recovery rehearsal','Certification practice','Operate a cluster through change and failure with explicit evidence.',
'''A cluster administrator must connect symptoms across applications, nodes and platform components. The capstone uses a separate multi-node lab and a set of controlled faults: bad placement, broken Service selection, node service interruption and storage misunderstanding.

Before injecting a fault, define the expected blast radius, the recovery route and the evidence to capture. Change one thing at a time. A task is complete only when the original acceptance condition works again.''',
'''The CKA domain map gives troubleshooting the largest share, so diagnosis must be practised, not left as a reading appendix. Include timed read-only triage before repair: context, namespace, object status, recent changes, Events and relevant component logs.

A local single-node cluster cannot prove highly available control-plane recovery or real cross-node networking. Keep those as separate VM exercises and record them as incomplete until actually performed. Professional depth adds change review, recovery rehearsal and incident communication beyond command speed.''',
'The bank platform must serve its page, schedule replacements, resolve internal names and preserve the learning marker after a controlled recovery. Each success criterion is checked independently.',
[('Prepare','Known-good state and recovery route'),('Diagnose','Collect evidence before one repair'),('Prove recovery','Retest service and platform dependencies')],
'Complete the CKA assessment task set. Use the multi-node/VM environment for its infrastructure tasks and local kind only for compatible workload tasks. Repeat unresolved faults until you can diagnose them without following an answer script.',
'Retain a change log, fault timeline, repair diff and repeated acceptance checks. Mark unavailable infrastructure exercises honestly rather than awarding yourself completion.',
'A reboot restores a node but the recurring disk-growth cause is unexplained. Write the prevention and monitoring follow-up before closing the incident.',
('Why does restoration alone not complete an incident investigation?','Service recovery is essential, but the unresolved cause can recur. Record cause, contributing conditions, prevention and follow-up verification.'),['https://github.com/cncf/curriculum/blob/master/CKA_Curriculum_v1.35.pdf','https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka/','tasks/debug/debug-cluster/'],mode='Timed VM / cluster practice',prereq='Complete CKAD and CKA lessons; disposable multi-node VM lab and tested recovery procedures.')
