from author import *
G='https://cloud.google.com/'
def cloud(id,title,domain,summary,understand,deep,case,nodes,lab,verify,fault,answer,refs,code='',mode='GCP lab / offline design',prereq='Complete cloud setup. Use your own isolated project and dummy data; cloud resources can incur charges. The offline alternative is a labelled design and predicted evidence, not an executed lab.',kind='flow'):
 add(id,'gcp',title,domain,summary,understand,deep,case,nodes,lab,verify,fault,answer,[u if u.startswith('http') else G+u for u in refs],code=code,mode=mode,prereq=prereq,kind=kind)
cloud('gcp-start','Cloud setup, projects and cost boundaries','ACE foundations','Establish identity, scope, location and a cleanup plan before provisioning.',
'''A Google Cloud project groups resources, enabled APIs, quotas and access policies. A billing account pays for linked usage; it is not the same thing as a project. A region is a geographical deployment area, while zones are separate locations within a region. Some services are regional, some zonal and some global.

Install the current gcloud CLI or use Cloud Shell. Select a project you are allowed to use. Start with read-only inventory. Set a budget alert and check pricing before creating anything: an alerts-only budget sends notifications; it does not cap spending. Free credits, free-tier eligibility and regional pricing must be checked separately.''',
'''The CLI account, active configuration, project and Application Default Credentials are related but different settings. A command can use explicit flags that override defaults. A script can therefore affect a different project from the one displayed in a browser. Record project ID, region and identity with every lab result.

API enablement grants availability of a service, not permission to use every resource. Quotas limit some operations but do not constitute a comprehensive spending stop. Build a resource inventory with an owner, location, creation purpose and cleanup command before starting. Never include real credentials in notes.''',
'Harbour Bank learning uses one isolated sandbox and fictional content. The design for a real enterprise would separate environments and responsibilities; the inexpensive lab intentionally avoids reproducing that full organisation.',
[('Identity and project','Who acts, and in which sandbox?'),('Location and limits','Region, APIs, quotas and budget'),('Evidence and cleanup','Inventory every created resource')],
'Run the read-only commands below. Replace the project ID in your shell before any later exercise. In the console, inspect billing linkage, budgets and the APIs dashboard. Write a cost/cleanup checklist. Offline: annotate a fictional inventory and identify which facts still require account verification.',
'Record the selected account, project ID and region without copying tokens. Identify the budget notification recipients and explain what happens if they ignore an alert.',
'A learner assumes a budget automatically stops a cluster. Identify the continuing billable resources and the separate action needed to remove them.',
('Does enabling an API create a free service entitlement?','No. Enablement permits API use; permissions, quotas, pricing and resource charges remain separate.'),['sdk/docs/install','resource-manager/docs/creating-managing-projects','billing/docs/how-to/budgets','docs/quotas/overview'],code='gcloud version\ngcloud auth list\ngcloud config list\nexport TK_PROJECT="YOUR_ISOLATED_PROJECT_ID"\nexport TK_REGION="us-central1"\ngcloud projects describe "$TK_PROJECT"\ngcloud services list --enabled --project="$TK_PROJECT"',prereq='A Google account and an authorised sandbox for live work. Reading and offline design need no account. No cloud resources are created by opening this guide.')
cloud('gcp-hierarchy','Organisation, folders and landing-zone decisions','ACE foundations','Structure ownership before scattering resources across projects.',
'''An organisation can contain folders and projects. Folders group projects for ownership and policy. Resources live under projects, but some controls and access are inherited from higher levels. Billing linkage is a separate relationship, so changing a folder does not itself move the bill.

A landing zone is a prepared foundation: identity, resource hierarchy, network boundaries, logging, billing and operational ownership. It is not one Google Cloud product. A small learner account without an organisation can still study these decisions using a diagram.''',
'''IAM allow policies inherited from ancestors can grant access that is not obvious from a project-only view. Deny policies and organisation policies address different questions: who may perform an action versus which configurations are permitted. Inspect effective controls, not only the policy nearest the resource.

Too many projects add administration; too few weaken isolation and cost accountability. Choose boundaries using environment, team autonomy, data sensitivity, quota needs and blast radius. Shared VPC centralises network ownership while service projects retain workload responsibility. Document exceptions rather than turning every exception into a new undocumented pattern.''',
'Propose bank-sandbox, bank-test and bank-production projects under environment folders, with a shared-network host project in the enterprise design. Only the sandbox is used for learning.',
[('Organisation / folders','Inherited governance and ownership'),('Projects','Environment and accountability boundaries'),('Resources','Workloads with effective policies')],
'Draw the proposed hierarchy and a separate billing relationship. Give each project an owner and three permitted actions. Use get-ancestors where your account supports an organisation, and compare actual ancestry with the design. Offline: identify where a broad inherited grant would reach.',
'The design explains why each boundary exists, where network ownership sits and how inherited access will be reviewed.',
'A project administrator removes a local grant but access remains. Investigate ancestor grants and group membership instead of repeatedly editing the same binding.',
('Is a billing account a parent in the resource hierarchy?','No. Billing association and organisation/folder/project ancestry are distinct relationships.'),['resource-manager/docs/cloud-platform-resource-hierarchy','architecture/landing-zones','vpc/docs/shared-vpc'],code='gcloud projects get-ancestors "$TK_PROJECT"\ngcloud projects get-iam-policy "$TK_PROJECT"',kind='architecture')
cloud('gcp-iam','IAM, service accounts and least privilege','ACE foundations','Grant a specific identity only the actions needed on the intended resource.',
'''A principal is an identity such as a user, group or service account. A role is a collection of permissions. A binding associates principals with a role on a resource, sometimes with a condition. Prefer a suitable predefined role at the narrowest practical scope over broad basic roles.

A service account represents a workload identity; it is not a human login shared by a team. Kubernetes ServiceAccounts and Google IAM service accounts are different resources. A person allowed to deploy software should not automatically be able to impersonate every privileged workload identity.''',
'''Permission to attach or impersonate a service account can become a path to its authority. Review both resource access and identity delegation. Short-lived federation or impersonation is preferable to distributing long-lived key files, but still requires narrowly designed trust.

Allow policies, deny policies, conditions, organisation controls and service-specific checks can all influence the result. An IAM grant may also take time to propagate. Use a denied action as evidence to investigate the exact principal, permission, resource and condition; do not “fix” every 403 by granting Owner.''',
'A bank report reader should read only the dummy report bucket. A release identity may deploy the information service without reading production financial data.',
[('Principal','User, group or workload identity'),('Binding and scope','Role on the intended resource'),('Decision and audit','Allowed action or explained denial')],
'Create a role matrix for viewer, deployer and report reader. Inspect existing policies and describe one predefined role. In an approved sandbox, have an administrator grant only the chosen narrow role, then test one intended read and one deliberately disallowed action. Offline: review the matrix for privilege escalation.',
'Record the principal, resource scope, allowed action and denied action. Explain service-account delegation separately from ordinary resource access.',
'A deployment fails with 403 and the proposed remedy is Owner. Identify the missing permission and the smallest justified role instead.',
('Does knowing a service-account email give permission to act as it?','No. Identity use and impersonation require explicit authority; the address is only an identifier.'),['iam/docs/overview','iam/docs/service-account-overview','iam/docs/best-practices-for-managing-service-account-keys'],code='gcloud iam roles describe roles/storage.objectViewer\ngcloud iam service-accounts list --project="$TK_PROJECT"\ngcloud projects get-iam-policy "$TK_PROJECT"')
cloud('gcp-network','VPC, subnets, routes, firewalls and private access','ACE foundations','A packet needs a route, permission and a reachable destination.',
'''A VPC network is global; its subnets are regional. IP ranges must be planned so connected networks do not overlap. Routes choose a path. Firewall policies permit or deny traffic along relevant boundaries. Neither a route nor a firewall rule creates an application listener.

Cloud NAT supports outbound connections and their return traffic for eligible resources without external IPv4 addresses; it is not a general unsolicited inbound entry point. Private Google Access and private service access solve other connectivity needs. Learn the destination and service model before choosing a mechanism.''',
'''For GKE, node, Pod and Service addressing interact with VPC design. Running out of Pod addresses can prevent growth even when CPU quota remains. A network plan therefore needs address capacity, security boundaries, DNS, egress and connectivity to managed dependencies.

Hybrid connections add VPN or Interconnect, route advertisement, redundancy, MTU and DNS decisions. Network reachability does not establish application authentication. Trace both directions of a connection and identify the exact control blocking it before broadening access.''',
'Place bank workloads in a dedicated regional subnet. The future report database has a private connection plan, while administrators reach the platform through an approved access path rather than exposing management ports to everyone.',
[('Address and route','VPC, subnet and destination path'),('Security boundary','Firewall and identity controls'),('Dependency access','DNS, private services and egress')],
'Inventory networks, subnets and firewall rules using read-only commands. Draw the route from a private workload to a Google API and separately to the public internet. Mark which path needs NAT or private access in your chosen design. Offline: use invented, non-overlapping CIDRs.',
'For each path, explain source, destination, DNS, route, firewall and authentication. Include an address-capacity estimate for cluster growth.',
'A private node cannot pull an external image. Verify DNS and outbound connectivity; adding an inbound web firewall rule does not repair egress.',
('Does Cloud NAT expose a private workload to arbitrary incoming internet connections?','No. It supports configured outbound connectivity and return traffic; inbound exposure requires a separate design.'),['vpc/docs/vpc','vpc/docs/routes','vpc/docs/firewalls','nat/docs/overview','vpc/docs/private-google-access'],code='gcloud compute networks list --project="$TK_PROJECT"\ngcloud compute networks subnets list --project="$TK_PROJECT"\ngcloud compute firewall-rules list --project="$TK_PROJECT"',kind='architecture')
cloud('gcp-compute','Choose VMs, managed containers or GKE','ACE foundations','Select the operating model from constraints, not from product popularity.',
'''Compute Engine supplies virtual machines and extensive OS control. Managed instance groups maintain VM fleets from templates and can scale them. Cloud Run runs supported container workloads with a managed execution model. GKE offers Kubernetes APIs and ecosystem integration with a managed control plane.

Choose using workload shape, required runtime control, team skills, scaling, networking, state, startup time and operational cost. A container image alone does not make every service the best fit. Different parts of one business system can reasonably use different platforms.''',
'''A VM group health check, application readiness check and user-level service indicator answer different questions. Autoscaling can add instances, but cannot repair a serial database bottleneck or incorrect concurrency handling. Stateless replicas need external state and retry-aware interactions.

Managed services transfer selected infrastructure duties to the provider; they do not transfer responsibility for access design, application bugs, data retention or cost. Document which patching, scaling and incident tasks remain with your team for each option.''',
'The tiny bank information page does not inherently require GKE. We choose GKE for Kubernetes learning. A production recommendation might favour a simpler managed container service, while a legacy OS-bound reporting engine could remain on VMs.',
[('Compute Engine / MIG','OS control and fleet responsibility'),('Cloud Run','Managed application execution'),('GKE','Kubernetes orchestration and ecosystem')],
'Write a decision record comparing all three for the information page and a long-running legacy report worker. Score operational effort, required control, scaling and cost assumptions. Use read-only inventory if a sandbox already contains examples; no resource creation is necessary.',
'The chosen option follows a stated requirement, with one rejected alternative and a condition that would change the decision.',
'A team chooses Kubernetes because the app is containerised. Identify whether it actually needs Kubernetes-specific capabilities.',
('Does using a managed service remove application security responsibilities?','No. The provider manages defined infrastructure layers; workload identity, code, data and configuration still need owners.'),['compute/docs/instance-groups','run/docs/overview/what-is-cloud-run','kubernetes-engine/docs/concepts/kubernetes-engine-overview'],code='gcloud compute instances list --project="$TK_PROJECT"\ngcloud run services list --project="$TK_PROJECT"\ngcloud container clusters list --project="$TK_PROJECT"',kind='comparison')
cloud('gcp-storage','Object storage, lifecycle and recovery','ACE operations','Treat durability, access, retention and recoverability as separate choices.',
'''Cloud Storage holds objects in buckets. An object store is not a general POSIX filesystem and does not automatically behave like a local disk. Choose location and storage class using access frequency, availability requirements and the costs of operations, retrieval and early deletion where applicable.

Uniform bucket-level access simplifies access management through IAM rather than mixing object ACLs. Public access prevention helps avoid unintended public sharing. Retention, versioning, soft deletion and lifecycle rules solve different problems; understand their interaction before promising deletion or recovery.''',
'''A lifecycle rule can change classes or delete objects when conditions match. That is an automated policy with consequences, not merely a label. Retained or recoverable versions can continue to consume storage and incur charges after an ordinary delete.

Encryption at rest is part of the service, while customer-managed keys add control and key-availability obligations. A bucket with no public access can still be accessed by an overprivileged identity. Verify both policy and an actual allowed/denied read.''',
'Store only dummy bank statements such as “Learning report: no financial data.” Give a report reader object-view permission and keep the bucket private. Record retention decisions as a learning design, not a legal banking compliance claim.',
[('Bucket policy','Location, access and protection'),('Object lifecycle','Create, read, version and expire'),('Recovery test','Restore the intended checkpoint')],
'In your sandbox, use the console to create a uniquely named private bucket in the chosen region, review retention/soft-delete defaults and upload one dummy text file. List and read it with your authorised identity. Delete the test object and bucket when permitted; inspect recoverable versions and retention before assuming billing ended. Offline: design the lifecycle table.',
'Capture location, access policy and the dummy response. Explain whether deleting the current object leaves recoverable copies and what costs may remain.',
'A cleanup attempt is blocked by retention. Explain why a retention control should not be enabled casually during a short-lived lab.',
('Is object versioning the same as a tested business recovery process?','No. You still need the right versions, access, dependencies and a verified restoration procedure.'),['storage/docs/introduction','storage/docs/uniform-bucket-level-access','storage/docs/lifecycle','storage/docs/soft-delete'],code='export TK_BUCKET="YOUR_UNIQUE_LAB_BUCKET"\ngcloud storage buckets describe "gs://$TK_BUCKET" --project="$TK_PROJECT"\ngcloud storage ls "gs://$TK_BUCKET"\n# Read only your known dummy object:\ngcloud storage cat "gs://$TK_BUCKET/learning-report.txt"')
cloud('gcp-data','Select a database and preserve business invariants','ACE foundations','Match transactions, access patterns and scale before choosing a database.',
'''Cloud SQL provides managed relational engines for familiar relational workloads. Spanner addresses distributed relational needs with its own design and cost considerations. Firestore is a document database; Bigtable targets large-scale key-oriented workloads; BigQuery is an analytical warehouse. These are not interchangeable stores with different logos.

Begin with reads, writes, transaction boundaries, latency, volume, consistency, recovery and operational skills. A balance transfer needs reliable business invariants. Kubernetes replicas do not make two unrelated database writes atomic.''',
'''For a hypothetical transfer, debit, credit and the immutable transfer record must obey the chosen transaction model. An idempotency key prevents a retried request from creating a second logical transfer when implemented with durable uniqueness and result handling. A network timeout leaves an uncertain result that must be reconciled, not blindly repeated.

Separate operational transactions from analytical queries when their load and latency needs differ. Replication is not automatically a backup: it may copy a bad write quickly. Database-specific point-in-time recovery, schema migration compatibility and a verified restore remain essential.''',
'The current lab serves only a static page. A future bank transfer service would need an explicitly designed ledger and database transaction model. A reporting warehouse can consume controlled copies rather than run every report against the live transaction path.',
[('Transactional store','Atomic business changes'),('Document / key access','Fit the query and consistency model'),('Analytics','Historical aggregation and exploration')],
'Create a data decision table for user preferences, transfer records and monthly aggregate reports. Walk through a timeout after a committed transfer and a duplicate retry. Write pseudocode with a durable idempotency record. No real financial system or cloud database is required for this design exercise.',
'Explain where atomicity lives, how duplicates are detected and which recovery checkpoint restores correct business state.',
'A proposal places an authoritative ledger in an eventually reconciled cache. Identify the lost-update, durability and audit questions before selecting a product.',
('Can a queue or Kubernetes restart guarantee exactly one financial effect?','No. Correct effects require application and storage semantics, such as durable idempotency and transactional boundaries.'),['sql/docs/introduction','spanner/docs/overview','firestore/docs/overview','bigtable/docs/overview','bigquery/docs/introduction'],mode='Offline architecture exercise',kind='comparison')
cloud('gcp-events','Events, queues, retries and idempotency','ACE operations','Decouple work without pretending delivery and business effects are identical.',
'''A publisher sends an event; a subscription makes it available to consumers. Pub/Sub supports asynchronous communication so a slow report generator does not need to block a user-facing request. Cloud Tasks serves a different task-dispatch model where a producer targets scheduled work.

A consumer must decide when to acknowledge success. If it crashes after changing data but before acknowledgement, delivery may be repeated. Design the effect to tolerate retries, and distinguish a delivery guarantee from an end-to-end business guarantee.''',
'''Retry limits, backoff, dead-letter handling, message retention and ordering requirements affect recovery. Ordering can reduce concurrency and has scope conditions. Exactly-once delivery features have documented boundaries; they do not make an arbitrary database update plus external email one atomic operation.

An outbox pattern can record a business change and an event intention in one database transaction. A separate publisher forwards that intention, while consumers deduplicate where needed. Observe backlog age as well as count: a small set of very old messages can hide a stuck customer workflow.''',
'A dummy statement-request event triggers a report worker. Each request has a stable ID so retrying the event does not create duplicate externally visible reports.',
[('Publish intention','Stable event ID and relevant metadata'),('Deliver and process','Retries, acknowledgement and deduplication'),('Recover failures','Backlog, dead-letter review and replay')],
'Offline, trace publish → process → write result → crash → redelivery using a table of event ID and stored result. For an optional sandbox lab, use the Pub/Sub console tutorial with dummy events, inspect a subscription backlog, and delete only the created topic/subscription afterward.',
'The second delivery produces the same logical result rather than a duplicate effect. The runbook says who investigates messages that cannot be processed.',
'A consumer acknowledges before persisting its result and crashes. Explain the lost-work window and change the processing boundary.',
('Does acknowledging receipt prove that a business operation completed?','No. Acknowledgement should follow the application’s durable success condition, subject to its processing design.'),['pubsub/docs/overview','pubsub/docs/exactly-once-delivery','tasks/docs/dual-overview','pubsub/docs/dead-letter-topics'],code='gcloud pubsub topics list --project="$TK_PROJECT"\ngcloud pubsub subscriptions list --project="$TK_PROJECT"')
cloud('gke-modes','GKE Autopilot and Standard responsibilities','GKE developer and administrator','Choose how much node management belongs to your team.',
'''GKE manages the Kubernetes control plane. Autopilot additionally manages much of the node infrastructure and applies workload constraints; Standard provides more control over node pools and configuration. Both still require correct application manifests, identity, networking and operational decisions.

Use current feature support and workload requirements when choosing. Privileged host access, unusual agents, specialised infrastructure and migration constraints need explicit review. Do not infer support or price solely from the mode name.''',
'''An Autopilot workload can receive defaults or adjusted requests according to current platform rules. Inspect the admitted Pod, not just your local YAML. Standard node pools introduce machine type, size, autoscaling, upgrade and security decisions that must have owners.

A regional control plane does not distribute application replicas correctly by itself. Node placement, topology constraints, storage, dependencies and capacity still determine the user’s experience. Regional availability and disaster recovery across regions are different designs.''',
'Use Autopilot for an optional managed-platform lab, then document what would justify Standard for a specialised bank workload. Keep the simpler local kind environment for most CKAD practice.',
[('Autopilot','Managed infrastructure with guardrails'),('Standard','More node-pool control and decisions'),('Shared responsibility','Workloads, identity, data and outcomes')],
'Compare the current GKE mode documentation against the bank page, a privileged diagnostic agent and a specialised compute job. Inspect a cluster if available. Produce an owner matrix for node patching, image updates, IAM, backups and workload probes.',
'Each responsibility has an explicit owner and a reason. Identify which local lab manifests may need adaptation before Autopilot admission.',
'A restricted workload is rejected and the team assumes Kubernetes YAML is universal. Inspect GKE admission requirements and choose a compatible workload or justified platform change.',
('Does Autopilot make application image patching Google’s responsibility?','No. Managed infrastructure duties do not remove ownership of your application image and dependencies.'),['kubernetes-engine/docs/concepts/autopilot-overview','kubernetes-engine/docs/concepts/cluster-architecture','kubernetes-engine/docs/concepts/autopilot-security'],code='gcloud container clusters list --project="$TK_PROJECT"',kind='comparison')
cloud('gke-first','Create, inspect and remove a learning GKE cluster','GKE developer and administrator','Connect cloud control-plane access to the Kubernetes workflow you already know.',
'''Creating a cluster requires an authorised project, billing, enabled APIs, available quota and a compatible network. Use a dedicated node service account with the documented minimum node role. This identity handles node-level operations; it is different from an application’s identity.

The commands below deliberately name the project, region, network and cluster. Replace every placeholder after reviewing the creation page. A dedicated kubeconfig prevents cloud credentials from overwriting your local lab configuration. Install the GKE authentication plugin through official instructions.''',
'''get-credentials configures client access; it does not grant every Kubernetes action. The network endpoint, Google authentication, IAM and Kubernetes authorization all matter. An account can list a cluster yet fail to access its API or create a workload.

Deploy a fresh copy of bank.yaml and inspect any Autopilot changes to resources. Use ClusterIP plus port-forward rather than creating a public load balancer for this first lab. Deletion must include verification of dependent resources and retained storage; a successful CLI exit alone is not your full cleanup evidence.''',
'The same fictional information page runs in a new managed cluster. Compare the resulting Pod resources and node information with kind, then explain the responsibilities now handled by GKE.',
[('Cloud provisioning','Project, node identity and cluster'),('Client access','Dedicated kubeconfig and authentication'),('Workload evidence','Ready Pods plus a verified response')],
'First create a reviewed node service account and grant roles/container.defaultNodeServiceAccount as described in the official guide; ensure the creator may act as it. Use an existing isolated lab VPC/subnet. Run the commands only after confirming cost. Verify the bank marker through localhost. Delete the named cluster and inspect remaining resources. Offline: annotate every prerequisite and predict the observations.',
'Record cluster location, API context, admitted Pod settings, page response and cleanup inventory. Cloud execution is learner-performed; the course authors did not provision your project.',
'get-credentials works but kubectl is forbidden. Identify the active principal and authorization layer rather than downloading a service-account key.',
('Does obtaining kubeconfig automatically grant cluster-admin?','No. Client connection settings and authentication are separate from authorization.'),['kubernetes-engine/docs/how-to/creating-an-autopilot-cluster','kubernetes-engine/docs/how-to/cluster-access-for-kubectl','kubernetes-engine/docs/how-to/service-accounts'],code='export TK_CLUSTER="tk-bank-learning"\nexport TK_NETWORK="YOUR_LAB_NETWORK"\nexport TK_SUBNET="YOUR_LAB_SUBNET"\nexport TK_NODE_SA="YOUR_NODE_SA@$TK_PROJECT.iam.gserviceaccount.com"\nexport KUBECONFIG="$PWD/gke-learning-kubeconfig"\ngcloud services enable container.googleapis.com --project="$TK_PROJECT"\ngcloud container clusters create-auto "$TK_CLUSTER" --project="$TK_PROJECT" --region="$TK_REGION" --network="$TK_NETWORK" --subnetwork="$TK_SUBNET" --service-account="$TK_NODE_SA" --release-channel=regular\ngcloud container clusters get-credentials "$TK_CLUSTER" --project="$TK_PROJECT" --region="$TK_REGION"\nkubectl config current-context\nkubectl apply -f bank.yaml\nkubectl -n tk-bank rollout status deployment/bank-web --timeout=600s\nkubectl -n tk-bank port-forward service/bank-web 8080:80\n# After verification, stop forwarding with Ctrl-C.\n# Delete ONLY this disposable cluster when finished with GKE lessons:\n# gcloud container clusters delete "$TK_CLUSTER" --project="$TK_PROJECT" --region="$TK_REGION"',prereq='An isolated billable project; container API; reviewed network/subnet; node service account and required grants; GKE auth plugin; bank.yaml. Check current regional pricing and quotas first.')
cloud('gke-identity','Workload Identity Federation for GKE','GKE developer and administrator','Let a named Kubernetes workload access a narrowly scoped cloud resource.',
'''A Kubernetes ServiceAccount identifies a Pod to Kubernetes. Workload Identity Federation for GKE allows eligible workloads to obtain short-lived Google Cloud credentials using that workload identity. It avoids placing a downloaded long-lived service-account key into a Kubernetes Secret.

One supported approach grants a resource role directly to the federated principal. Another uses IAM service-account impersonation when needed for supported service or application requirements. These are alternative configurations, not steps that must always be combined.''',
'''The identity includes the workload pool, namespace and Kubernetes ServiceAccount name. Misstating any of them can bind permission to the wrong subject. Trust scope and Kubernetes permissions matter too: someone able to run arbitrary Pods as a privileged ServiceAccount can potentially exercise its cloud permissions.

Autopilot enables the relevant managed identity integration; Standard requires the appropriate cluster/node-pool configuration. Application credential discovery must use the intended identity path. Test a permitted operation and a denied operation; successful Pod startup is not proof of Google API access.''',
'The bank report-reader Pod uses a dedicated KSA and may read only the dummy bucket. It cannot upload objects or read unrelated buckets. Node identity is not reused as the application identity.',
[('Pod and KSA','Named namespace/workload identity'),('Federated credentials','Short-lived identity through GKE'),('Resource IAM','Allow only the intended bucket read')],
'Follow the linked direct-resource-access walkthrough using your dummy bucket. Create bank-reports in tk-bank, derive the project number, and grant objectViewer to its exact principal on that bucket. Run the official test Pod configured with serviceAccountName bank-reports. Compare a dummy read with a denied write. Remove the binding after the lab. Offline: trace identity and trust without inventing token contents.',
'Capture the KSA name, redacted principal construction, successful dummy read and denied write. Do not store token output. Confirm no downloaded key file was used.',
'The bucket role exists but names the default namespace. Compare the bound principal with the actual Pod’s namespace and ServiceAccount.',
('Is a KSA automatically the same object as an IAM service account?','No. They are separate identities. Federation or an explicitly configured impersonation relationship connects access where required.'),['kubernetes-engine/docs/concepts/workload-identity','kubernetes-engine/docs/how-to/workload-identity'],code='kubectl -n tk-bank create serviceaccount bank-reports\nexport TK_PROJECT_NUMBER="$(gcloud projects describe "$TK_PROJECT" --format="value(projectNumber)")"\nexport TK_PRINCIPAL="principal://iam.googleapis.com/projects/$TK_PROJECT_NUMBER/locations/global/workloadIdentityPools/$TK_PROJECT.svc.id.goog/subject/ns/tk-bank/sa/bank-reports"\ngcloud storage buckets add-iam-policy-binding "gs://$TK_BUCKET" --member="$TK_PRINCIPAL" --role=roles/storage.objectViewer\n# Run the linked official test Pod using this KSA; never print credentials.\n# After collecting evidence:\n# gcloud storage buckets remove-iam-policy-binding "gs://$TK_BUCKET" --member="$TK_PRINCIPAL" --role=roles/storage.objectViewer')
cloud('gke-network','GKE networking, exposure and policy','GKE developer and administrator','Separate cluster service discovery from VPC and external traffic.',
'''Pod networking, Service addressing and external exposure are different layers. A ClusterIP is for cluster-internal service access. A LoadBalancer Service requests an implementation-specific load balancer. Ingress or Gateway can express richer routing when a compatible controller and configuration are present.

GKE networking choices include IP allocation, endpoint access, dataplane features and network policy. Dataplane V2 uses an eBPF-based implementation; it does not make every traffic path or security control identical to another cluster.''',
'''External traffic can depend on forwarding rules, health checks, firewall permissions, backend readiness, route status and TLS. A Pod serving localhost in its container can still be unreachable from a backend health check. Keep Kubernetes and cloud evidence together.

Private nodes do not imply a private control-plane endpoint, nor do they guarantee working egress to every registry. Network policies, VPC firewall rules and IAM act at different boundaries. Design and test both permitted and forbidden paths; a diagram with a lock icon is not evidence of isolation.''',
'The bank learning page stays behind port-forward initially. A later exposure design introduces a Gateway and certificate while retaining explicit internal access to reports and an isolated data dependency.',
[('Inside the cluster','Pod IPs, DNS and Service endpoints'),('At the boundary','Gateway / load balancer and health'),('Across the VPC','Firewall, egress and private access')],
'Inspect the cluster network configuration and bank EndpointSlices. Draw browser → external entry → Service/backend → Pod and label which addresses and resources are real in your lab. If you add a GKE Gateway, use the current controller guide, verify status and an actual request, then remove cloud load-balancing resources as part of cleanup. Offline: identify the checks for a 503.',
'Explain every boundary and distinguish a programmed route from a healthy response. Identify where policy is actually enforced.',
'All Pods are Ready but the external backend is unhealthy. Compare health-check path/port, firewall and routing instead of scaling replicas blindly.',
('Does a private node configuration prove all cluster access is private?','No. API endpoint exposure, workload ingress and outbound connectivity are separate settings.'),['kubernetes-engine/docs/concepts/alias-ips','kubernetes-engine/docs/concepts/dataplane-v2','kubernetes-engine/docs/concepts/gateway-api','kubernetes-engine/docs/concepts/network-overview'],code='gcloud container clusters describe "$TK_CLUSTER" --region="$TK_REGION" --project="$TK_PROJECT"\nkubectl -n tk-bank get service,endpointslices\nkubectl get networkpolicies -A',kind='architecture')
cloud('gke-lifecycle','Release channels, scaling and disruption budgets','GKE developer and administrator','Keep infrastructure current while protecting application service.',
'''A release channel controls the stream of GKE versions and upgrade behaviour. Maintenance windows and exclusions influence timing within supported limits; they do not promise indefinite avoidance of required updates. Review current lifecycle rules and support dates.

Workload autoscaling changes replicas or resource recommendations. Infrastructure autoscaling changes available capacity according to the platform mode and constraints. These loops are related but distinct. A replica request can remain unsatisfied because of quota, address space, storage topology or incompatible placement.''',
'''A PodDisruptionBudget protects against some voluntary disruptions through the eviction path. It cannot prevent every node failure, application crash or involuntary disruption. Too-strict budgets combined with unhealthy replicas can obstruct maintenance without creating more actual resilience.

Before an upgrade, check deprecated APIs, webhooks, CNI/CSI dependencies, node characteristics and application acceptance tests. Stage changes in a representative environment and retain evidence. Avoid scaling down solely because average CPU looks low when peak latency or memory is the real constraint.''',
'The bank page uses two or more replicas, meaningful readiness and a reviewed disruption budget. A maintenance rehearsal tests actual page availability while a node is replaced rather than claiming success from the final Ready count.',
[('Version policy','Channel, support and maintenance'),('Capacity loops','Replica demand and available nodes'),('Service verification','Disruption tolerance and request tests')],
'Inspect cluster release-channel configuration and workload resources. Build a maintenance checklist and rehearse Pod replacement in the local lab. In GKE, inspect upgrade notifications and autoscaler decisions without forcing an unsupported downgrade. Offline: analyse a Pending Pod with exhausted quota.',
'Identify which component scales, what metric drives it and what can block it. State whether your evidence covers a Pod restart, node replacement or control-plane upgrade.',
'An HPA asks for more Pods but no node capacity arrives. Check requests, quotas, topology and autoscaler evidence before lowering readiness standards.',
('Does a disruption budget guarantee zero downtime?','No. It is one voluntary-disruption control; capacity, health, routing, state and involuntary failures still matter.'),['kubernetes-engine/docs/concepts/release-channels','kubernetes-engine/docs/concepts/cluster-autoscaler','kubernetes-engine/docs/concepts/maintenance-windows-and-exclusions'],code='kubectl -n tk-bank get deployment,hpa,pdb\nkubectl -n tk-bank get events --sort-by=.metadata.creationTimestamp\ngcloud container operations list --project="$TK_PROJECT" --region="$TK_REGION"')
cloud('gcp-delivery','Artifact Registry, build provenance and progressive delivery','ACE operations','Promote a traceable artifact through verified environments.',
'''Artifact Registry stores build artifacts such as container images. A build pipeline produces an image, tests it and records evidence. A deployment pipeline changes an environment to run a selected artifact. Separating build from promotion helps ensure the tested image is the one being deployed.

An image tag is a convenient name that may move. A digest identifies content. Pin an approved digest for reproducible promotion, while planning how new security updates will be built and released. Do not place cloud secrets in image layers or source repositories.''',
'''Cloud Build can execute builds and Cloud Deploy can manage supported delivery targets and rollout processes. Pipeline identities need carefully bounded authority. A build that can deploy production without review collapses a useful trust boundary even if every step has a green status.

Scanning, provenance and admission policy are complementary controls. A scan result is time-dependent and not proof of zero vulnerabilities. Binary Authorization can enforce configured deployment policy for supported targets, but application correctness and data migration safety still require tests and a rollback/forward-fix plan.''',
'Promote one bank information-page digest from test to a small production canary. Verify the marker and request health before increasing exposure. Keep any database migration backward compatible through the transition.',
[('Build and attest','Source, tests and artifact digest'),('Approve and promote','Environment-specific release authority'),('Observe and recover','Canary evidence and rollback limits')],
'Create an offline release evidence sheet: source revision, image digest, test result, approver, target and recovery action. Optionally use an isolated Artifact Registry repository and the official build quickstart with the dummy page; record identity permissions and delete stored artifacts afterward. Compare an image change with a database schema change.',
'The same digest appears in build evidence and the running Pod specification. Explain what an image rollback does not undo.',
'A pipeline rebuilds a mutable tag separately in production. Identify why passing tests in staging no longer proves the deployed bytes were tested.',
('Does an image digest prove that the image is safe?','No. It identifies content. Security, correctness, provenance and authorization need additional evidence.'),['artifact-registry/docs/overview','build/docs/overview','deploy/docs/overview','binary-authorization/docs/overview'],code='gcloud artifacts repositories list --project="$TK_PROJECT"\nkubectl -n tk-bank get deployment bank-web -o yaml\n# Compare spec image digest with your approved release evidence.',kind='flow')
cloud('gcp-iac','Infrastructure as code, state and change review','ACE operations','Make infrastructure intent reviewable and repeatable.',
'''Infrastructure as code records desired resources in versioned files. Terraform plans differences and applies supported changes through provider APIs. State associates configuration with managed objects; it is not merely a disposable cache.

A plan is a proposal based on current information, not an unconditional guarantee. Review replacements, identity permissions, dependencies and cost before applying. Start with a small isolated resource and name every variable rather than copying a large production template blindly.''',
'''State can contain sensitive values even when terminal output hides them. Protect the backend, access, locking and recovery. Concurrent writers and out-of-band changes create drift and confusion. Importing an existing resource needs care so configuration describes the actual intended lifecycle.

A successful infrastructure apply does not prove the application works. Follow it with configuration checks and service acceptance tests. Separate secrets from source, pin appropriate provider/module versions and use an authorised delivery identity for changes.''',
'The bank platform records network and cluster intent separately from workload manifests. A pull-request review checks destructive replacements before the plan is approved for the sandbox.',
[('Configuration','Versioned intent and variables'),('Plan and state','Match resources and review change'),('Apply and verify','Provision, then test real outcomes')],
'Create an original pseudocode module interface for project, region, network and labels. Review the linked Google Cloud Terraform tutorial before a live apply. If Terraform is available, run fmt and validate on a local configuration; use plan only with an authorised sandbox. Offline: annotate a hypothetical plan replacing a stateful resource.',
'Your review identifies state protection, destructive changes, drift and post-apply tests. Do not claim a plan was executed when only a design was reviewed.',
'A developer commits a state file because it looks like JSON documentation. Identify sensitive content risk and the intended protected backend.',
('Does terraform validate confirm that cloud permissions and quota will allow apply?','No. Validation checks configuration consistency; live planning and execution have additional dependencies.'),['docs/terraform/terraform-overview','docs/terraform/best-practices/general-style-structure','docs/terraform/resource-management/store-state'],code='# In a reviewed Terraform learning directory:\nterraform fmt -check\nterraform validate\n# Run plan/apply only after configuring your authorised isolated project.')
cloud('gcp-observe','Cloud operations: logs, metrics, alerts and SLOs','ACE operations','Monitor the experience users receive and the dependencies that explain it.',
'''Cloud Logging records supported log data and Cloud Monitoring provides metrics, dashboards and alerting. An SLI measures an outcome; an SLO defines a target over a window. A service can have healthy infrastructure metrics while returning the wrong content or failing a critical workflow.

Choose a small set of meaningful indicators: valid request success, latency, data freshness and correctness checks where appropriate. Route actionable alerts to an owner with a runbook. A dashboard nobody interprets is not an incident response capability.''',
'''If a monthly request-success target is 99.9%, the error budget is 0.1% of the measured valid requests in that window. This is not automatically the same as a fixed number of downtime minutes. Define exclusions, sampling, missing data and denominator carefully before using a percentage.

Logs and metrics have access, retention, cardinality and ingestion costs. Audit logging and application logging have different coverage. Redact sensitive values and protect investigation access. Test the alert path, including notifications, instead of assuming an enabled policy reaches a responder.''',
'The bank page check requests the page and verifies its marker. A second signal checks elevated failure rates. The incident note correlates rollout time, Pod state and user-level errors without exposing account data.',
[('Measure outcome','Requests, latency and valid evidence'),('Correlate signals','Logs, metrics, traces and changes'),('Act with ownership','Alert, runbook and recovery check')],
'Write one SLI definition and calculate a request-based error budget for 200,000 requests at 99.9% success: 200 failed requests are the full budget. Inspect recent dummy-workload logs if running GKE. Design and test a low-volume non-paging notification only in your own lab. Offline: diagnose an evidence timeline.',
'The indicator has a clear numerator, denominator and window. Your alert has an owner, response and test result, or is explicitly marked untested.',
'No failures appear because the telemetry pipeline stopped. Add signal-health checks and independent synthetic requests.',
('Is a 99.9% request SLO necessarily a promise of exactly 43.2 minutes downtime per month?','No. Request-based and time-based SLIs have different denominators; traffic distribution and window definitions matter.'),['monitoring/docs/monitoring-overview','logging/docs/overview','stackdriver/docs/solutions/slo-monitoring','architecture/framework/operational-excellence'],code='gcloud logging read \'resource.type="k8s_container"\' --project="$TK_PROJECT" --limit=10 --format=json\n# Use only dummy workloads; redact identifying and sensitive log fields.')
cloud('gcp-security','Threat models, secrets, keys and policy boundaries','PCA architecture','Design controls around assets, identities and plausible failure paths.',
'''A threat model identifies valuable assets, trust boundaries, potential misuse and mitigations. For a cloud workload, examine user entry, workload identity, image delivery, data access, administration and recovery. Each control should address a stated threat rather than decorate a diagram.

Secret Manager stores secrets with version and access controls. Cloud KMS manages cryptographic keys. They solve related but different problems. IAM limits actions, organisation policies restrict configurations, and VPC Service Controls can reduce supported-service data-exfiltration paths. None replaces the others.''',
'''A customer-managed encryption key adds responsibilities for permissions, rotation, availability and recovery. Disabling a key can make protected data unavailable; it is not a casual incident toggle. Secrets must be rotated with application compatibility and rollback in mind.

Separate preventive, detective and recovery controls. A blocked public bucket does not prevent an authorised but compromised workload from reading data it is allowed to access. Reduce authority, observe unusual behaviour and rehearse response. Compliance statements need actual requirements and evidence; architecture diagrams alone cannot certify compliance.''',
'The bank report worker receives only read access to dummy reports. The release identity cannot alter IAM. An incident runbook explains how to revoke workload access and verify recovery without deleting the data.',
[('Assets and boundaries','Data, identities and supply chain'),('Controls','Least privilege, secrets and policy'),('Evidence and response','Audit, containment and verified recovery')],
'Draw a threat model with five trust boundaries. For each, write one abuse case, a preventive control and an observable signal. Inspect only metadata for existing sandbox secrets; never print secret payloads. Offline: rehearse a leaked-key scenario and prefer eliminating static keys where possible.',
'The control matrix maps each threat to an owner and a verification step, and acknowledges residual risk and service limitations.',
'A proposal claims encryption eliminates the need for IAM. Explain why an authorised attacker can still request plaintext through the service.',
('Are Secret Manager and KMS interchangeable?','No. Secret Manager manages secret values and versions; KMS manages cryptographic keys and operations used by supported integrations.'),['secret-manager/docs/overview','kms/docs/key-management-service','vpc-service-controls/docs/overview','resource-manager/docs/organization-policy/overview','architecture/framework/security'],code='gcloud secrets list --project="$TK_PROJECT"\n# Do not run secret payload access commands for documentation screenshots.',kind='architecture')
cloud('gcp-recovery','Backups, regional failure and disaster recovery','PCA architecture','Recover the business service, not merely its Kubernetes objects.',
'''RPO expresses acceptable data loss measured back from an incident; RTO expresses the target time to restore the defined service. These are objectives agreed with stakeholders, not automatic properties of a product. Measure actual restoration results against them.

A recovery design includes configuration, application artifacts, persistent data, identities, networking and dependent services. Availability within a region and recovery after a regional failure need different evidence. Replication may improve availability while also replicating accidental deletion.''',
'''Backup for GKE can protect selected Kubernetes resources and supported volume data, but it is not a backup of the entire cloud project. Cluster infrastructure, node-pool configuration, registry images and external data services require their own recovery arrangements. A target cluster and correct permissions are part of the restoration path.

Cross-region recovery adds location constraints, quotas, keys, DNS, data replication lag and consistency decisions. A warm standby costs more than rebuilding from backups but may meet a shorter RTO. Never claim an RTO based solely on the configured backup schedule.''',
'For the learning bank page, Git content plus available images and infrastructure configuration may be enough to rebuild. A future ledger needs a separate database recovery procedure and reconciliation of incomplete transfers.',
[('Checkpoint each dependency','Objects, data, images and infrastructure'),('Restore the service','Capacity, identity and correct order'),('Prove business recovery','Known records, requests and measured time')],
'Build a recovery inventory with owner, backup method, location and restore test. Restore the local PVC marker into a separate learning workload where supported. For GKE backup practice, follow the official supported-resource guide in a billable sandbox. Offline: simulate losing the original region and identify missing dependencies.',
'Report measured versus target recovery time, the latest verified data checkpoint and anything not restored. Include application-level checks.',
'A backup plan covers Kubernetes manifests but omits the external database. Identify the false sense of recoverability and assign a separate database test.',
('Does Backup for GKE automatically capture Cloud SQL databases and all project infrastructure?','No. Those dependencies need their own backup or rebuild plans and coordinated verification.'),['kubernetes-engine/docs/add-on/backup-for-gke/concepts/backup-for-gke','architecture/dr-scenarios-planning-guide','architecture/framework/reliability'],kind='architecture')
cloud('gcp-cost','Capacity, cost and sustainable operation','PCA architecture','Compare complete operating cost against measurable service needs.',
'''Cloud cost includes compute, storage, operations, network transfer and supporting services such as logs or load balancers. Estimate a complete workload, not only the price of one VM. State region, utilisation, data volume and retention assumptions next to the estimate.

Rightsizing matches resources to observed demand with headroom. Autoscaling can reduce idle capacity but needs limits and trustworthy metrics. Commitments suit sufficiently predictable usage; interruptible capacity suits workloads that can tolerate interruption and retry.''',
'''A lower unit price may increase total cost if it causes longer runtime, excessive retries or operational complexity. Cross-zone/region traffic and data access patterns can change an apparently cheap design. Measure cost per useful outcome, such as a completed dummy report, alongside latency and failure rate.

Sustainability decisions include avoiding unnecessary work, selecting efficient resources and considering location constraints and available environmental data. Do not claim a precise carbon saving without a supported methodology. Financial and sustainability trade-offs still need security, reliability and data-location constraints.''',
'The bank sandbox should not keep an oversized cluster running between exercises. The production design estimates a steady baseline, peak scaling and retained data separately before considering purchasing commitments.',
[('Demand and constraints','Workload, latency and recovery needs'),('Resource model','Capacity, transfer, storage and telemetry'),('Measure and improve','Unit cost with service quality intact')],
'Create a monthly estimate using the current calculator for a stated region and workload. Include logs, load balancing, storage and transfer. Compare idle and peak cases, then list shutdown/retention actions for the lab. Offline: use labelled illustrative units rather than inventing current prices.',
'Every cost has an assumption and source/date. The recommended saving does not silently worsen a required SLO or recovery objective.',
'A learner deletes the VM but leaves disks, addresses and snapshots. Inspect the inventory and explain which resources can continue to cost money.',
('Is a budget alert a substitute for reviewing resource inventory?','No. Alerts help detect spending, while ownership, inventory and deliberate cleanup control what continues to run.'),['products/calculator','architecture/framework/cost-optimization','architecture/framework/sustainability','billing/docs/how-to/budgets'],mode='Offline architecture / optional GCP billing review',kind='flow')
cloud('gcp-migration','Migration, hybrid connectivity and data cutover','PCA architecture','Move dependencies and operations, not just compute instances.',
'''A migration starts with an inventory of applications, owners, dependencies, data, network paths and business constraints. Rehosting changes where a workload runs; replatforming changes selected platform services; refactoring changes application design. Choose per workload rather than imposing one strategy on everything.

Plan pilot, migration waves, validation, cutover and recovery. Data movement requires a consistency boundary: which system accepts writes, how changes replicate, when clients switch and what happens if validation fails.''',
'''A rollback after new writes reach the target is more complicated than changing DNS back. The source may now be stale. Define reconciliation and reverse-data strategy before permitting target writes. DNS caching, sessions, certificates and third-party callbacks can extend a cutover beyond the visible deployment.

Hybrid operation adds identity, routing, latency, observability and support ownership across environments. A cloud dependency that performs poorly over a high-latency link may require redesign or colocating the workload. Rehearse with realistic data shape and traffic while protecting sensitive information.''',
'Move the bank information page first as a low-risk pilot. Treat a hypothetical ledger migration as a separate programme with data reconciliation and an explicit write-freeze or replication strategy.',
[('Discover and plan','Dependencies and migration strategy'),('Move and validate','Pilot, data sync and cutover checks'),('Operate and improve','Ownership, recovery and measured outcomes')],
'Write a cutover runbook with decision gates, responsible people, data checkpoints, client changes and abort criteria. Walk through failure immediately before and after the first target write. Offline work is the main exercise; do not migrate real financial data.',
'The runbook distinguishes application rollback from data reconciliation and gives an owner for each decision.',
'The plan says “switch DNS back” after a failed target write. Identify divergent data and the missing reconciliation procedure.',
('Why is a post-write rollback harder than a pre-cutover abort?','The target may contain new authoritative changes absent from the source. Reverting traffic alone can lose or duplicate effects.'),['architecture/migration-to-gcp-getting-started','architecture/migration-to-google-cloud-transferring-your-large-datasets','network-connectivity/docs/vpn/concepts/overview','network-connectivity/docs/interconnect/concepts/overview'],mode='Offline architecture exercise')
cloud('gcp-architecture','Architecture decisions and the Well-Architected review','PCA architecture','Make trade-offs explicit enough for another person to challenge.',
'''An architecture connects requirements to responsibilities, interfaces, data, deployment and operations. Start with business outcomes and measurable constraints: peak demand, acceptable latency, recovery targets, access boundaries, team capability and cost. Product selection comes after those questions.

A decision record states context, options, choice and consequences. A diagram shows relationships, but prose explains why they exist and where assumptions remain. Review operational excellence, security, reliability, performance, cost and sustainability together rather than optimising one pillar in isolation.''',
'''Distinguish functional requirements from quality attributes. “Show a balance” is behaviour; “respond within a defined percentile under stated load” is a measurable quality target. Unknown traffic, regulations or recovery needs are open questions, not excuses to invent precision.

Use sensitivity analysis: what changes if demand rises tenfold, a region fails or the team halves? An architecture that requires expertise the team does not possess has an operational risk even if the component diagram is technically plausible. Record rejected options and a revisit trigger.''',
'For a future bank platform, compare a simpler managed application design with a GKE design. Separate the information page, transaction authority, reporting, identity and audit responsibilities. Never imply the teaching page implements this production system.',
[('Business and constraints','Outcomes and measurable qualities'),('Options and decisions','Trade-offs and ownership'),('Evidence and review','Tests, risks and revisit conditions')],
'Produce a context diagram, deployment diagram and two decision records for the bank case. Have a peer challenge cost, failure recovery and access assumptions. Offline: replace the peer with a written adversarial review using the six framework perspectives.',
'Each chosen component supports a requirement. The review includes one meaningful trade-off, unresolved assumption and planned experiment.',
'A proposal adds every cloud product to appear enterprise-ready. Remove components that have no stated requirement or owner.',
('Can the technically most flexible platform be the wrong architecture?','Yes. Skills, operating cost, complexity, reliability needs and delivery constraints can make a simpler alternative better.'),['architecture/framework','architecture/architecture-decision-records','learn/certification/cloud-architect'],mode='Offline architecture exercise',kind='comparison')
cloud('gcp-ai','AI systems, retrieval and model-serving architecture','PCA architecture','Apply architecture discipline to probabilistic components and sensitive context.',
'''An AI feature needs a defined user task, authorised data and measurable evaluation. Retrieval-augmented generation supplies selected context to a model; it does not guarantee the answer is correct. Training, fine-tuning, inference and retrieval are different activities with different costs and data responsibilities.

Choose between managed model APIs, managed custom model services and specialised infrastructure according to control, latency, data handling, scale and team skills. Google’s current architecture exam guide includes AI/ML platform topics; consult the current product documentation as names and capabilities evolve.''',
'''A retrieval pipeline has ingestion, transformation, indexing, permission-aware retrieval, model invocation and response evaluation. Documents can contain malicious instructions; retrieved text must remain untrusted data. Prevent unauthorised retrieval before generation and test for leakage, unsupported answers and prompt injection.

Model serving introduces batching, accelerator capacity, startup time, quotas and cost per useful response. Evaluation must include task quality and operational latency/error behaviour. A deterministic fallback or human escalation may be more appropriate than always producing an answer. A model cannot authorise a transfer simply because it produced plausible text.''',
'The bank prototype adds an optional assistant for public help articles only. It cites approved fictional help content and hands off account-specific requests. It never sees real balances or gains permission to move money.',
[('Approved knowledge','Permission-aware ingestion and retrieval'),('Model interaction','Bounded task, context and guardrails'),('Evaluation and fallback','Quality, leakage, latency and escalation')],
'Offline, create five public-help questions, two unanswerable questions and two hostile retrieved passages. Specify the expected response behaviour and score groundedness, refusal/escalation and leakage. Draw separate retrieval and model-serving dependencies. No paid AI API is required.',
'The evaluation includes failures and an explicit fallback. Explain which claims require a real model test rather than a paper design.',
'A retrieved help article instructs the assistant to reveal secrets. Keep it as untrusted source content and test that it cannot override the application’s authority boundaries.',
('Does adding retrieval eliminate hallucinations?','No. Retrieval can improve grounding, but source quality, permissions, model behaviour and evaluation still matter.'),['vertex-ai/docs/start/introduction-unified-platform','vertex-ai/generative-ai/docs/rag-overview','architecture/framework/perspectives/ai-ml','learn/certification/cloud-architect'],mode='Offline architecture and evaluation exercise',kind='architecture')
cloud('gcp-capstone','ACE operations and PCA architecture capstones','Independent practice','Demonstrate operational evidence and defend architecture decisions separately.',
'''The ACE practice path asks you to inspect and operate an isolated environment: project, IAM, network, workload, observability and cleanup. The PCA practice path asks you to evaluate requirements, choose an architecture, explain trade-offs and plan reliable operations. These abilities reinforce each other but are not the same assessment.

Our practical tasks and scenario reviews are original learning exercises, not replicas of Google’s exams or official scoring. Use the current official standard exam guides to plan preparation. Reading the guide and passing a self-check do not by themselves establish professional experience.''',
'''Build an evidence portfolio: a reproducible lab record, two fault investigations, a restore rehearsal, an architecture decision and an operational handover. Repeat tasks with changed constraints so you learn reasoning rather than a memorised command sequence.

For SME development, continue beyond certification into observed incidents, capacity experiments, security reviews, migration rehearsal and reviewed team decisions. Distinguish a design you can explain from a system you have operated under failure. Keep cloud/VM tasks marked pending until actually run.''',
'The final Harbour Bank design separates the implemented learning page from a proposed transaction platform. Its portfolio labels each claim as observed, documented, calculated or assumed.',
[('ACE evidence','Operate and troubleshoot deliberately'),('PCA judgement','Defend options and failure recovery'),('Continued practice','Repeat with new constraints and review')],
'Complete the ACE and PCA assessment pages independently. Use a sandbox for live tasks or label the offline alternative clearly. Review against the criteria, correct gaps and repeat without following the sample reasoning.',
'A reviewer can reproduce your commands or follow your design argument. No unexecuted cloud task is presented as a successful test.',
'A portfolio lists many products but cannot explain a failed request. Return to one complete request path and gather evidence at each boundary.',
('What is stronger evidence than marking every lesson complete?','A reproducible observation, an explained diagnosis, a tested recovery and a decision defended against changed requirements.'),['learn/certification/cloud-engineer','learn/certification/cloud-architect','https://services.google.com/fh/files/misc/professional_cloud_architect_exam_guide_english.pdf'],mode='Independent GCP practice / offline review')
