from pathlib import Path
import sys,json,re
ROOT=Path(__file__).resolve().parent
sys.path.insert(0,str(ROOT/'src'))
import ckad
from author import LESSONS
for name in ([] if '--ckad-only' in sys.argv else ['cka','gcp']):
 if (ROOT/'src'/f'{name}.py').exists():__import__(name)
commands={
'starter':'kubectl apply -f bank.yaml\nkubectl -n tk-bank rollout status deployment/bank-web --timeout=120s\nkubectl -n tk-bank get endpointslices -l kubernetes.io/service-name=bank-web\nkubectl -n tk-bank port-forward service/bank-web 8080:80\n# In another terminal: curl http://127.0.0.1:8080',
'init-sidecars':'kubectl apply -f init.yaml\nkubectl -n tk-bank wait --for=condition=Ready pod/bank-init --timeout=120s\nkubectl -n tk-bank get pod bank-init -o yaml\nkubectl -n tk-bank exec bank-init -- cat /usr/share/nginx/html/index.html',
'jobs':'kubectl apply -f jobs.yaml\nkubectl -n tk-bank wait --for=condition=complete job/bank-report --timeout=120s\nkubectl -n tk-bank logs job/bank-report\nkubectl -n tk-bank create job report-now --from=cronjob/bank-report-schedule\nkubectl -n tk-bank wait --for=condition=complete job/report-now --timeout=120s\nkubectl -n tk-bank logs job/report-now',
'secrets':'kubectl apply -f secret-reader.yaml\nkubectl -n tk-bank get pod secret-reader\nkubectl -n tk-bank logs secret-reader\nkubectl auth can-i get secrets -n tk-bank',
'resources':'kubectl apply -f pending.yaml\nkubectl -n tk-bank describe pod bank-pending\nkubectl -n tk-bank delete pod bank-pending',
'identity-rbac':'kubectl apply -f rbac.yaml\nkubectl auth can-i get pods -n tk-bank --as=system:serviceaccount:tk-bank:bank-reader\nkubectl auth can-i get secrets -n tk-bank --as=system:serviceaccount:tk-bank:bank-reader',
'security-context':'kubectl apply -f security.yaml\nkubectl -n tk-bank wait --for=condition=Ready pod/secure-worker --timeout=120s\nkubectl -n tk-bank logs secure-worker\nkubectl -n tk-bank exec secure-worker -- sh -c "echo blocked > /root-test"\n# The last command should fail: the root filesystem is read-only.',
'storage':'kubectl apply -f storage.yaml\nkubectl -n tk-bank wait --for=condition=Ready pod/bank-storage --timeout=120s\nkubectl -n tk-bank exec bank-storage -- sh -c "echo retained > /data/marker"\nkubectl -n tk-bank delete pod bank-storage\nkubectl apply -f storage.yaml\nkubectl -n tk-bank wait --for=condition=Ready pod/bank-storage --timeout=120s\nkubectl -n tk-bank exec bank-storage -- cat /data/marker\nkubectl get pv',
'network-policy':'# Basic kind: schema check only.\nkubectl apply --dry-run=server -f policy.yaml\n# Apply and test traffic only in the documented enforcing environment.\n# kubectl apply -f policy.yaml',
'ingress':'kubectl apply --dry-run=server -f ingress.yaml\nkubectl get ingressclass\n# Set the actual installed class before live application.',
'extensions':'kubectl apply -f reports-crd.yaml\nkubectl wait --for=condition=Established crd/bankreports.learning.techknowen.example --timeout=60s\nkubectl apply -f report.yaml\nkubectl -n tk-bank get bankreports\n# No report controller is installed by this example.'}
domains={'ckad':[{'title':'Application Design and Build','weight':'20%','lessons':['images','pod-design','init-sidecars','workload-choice','jobs','storage']},{'title':'Application Deployment','weight':'20%','lessons':['rollouts','release-strategies','helm','kustomize']},{'title':'Application Observability and Maintenance','weight':'15%','lessons':['probes','debugging','api-versions']},{'title':'Application Environment, Configuration and Security','weight':'25%','lessons':['configuration','secrets','resources','identity-rbac','security-context','extensions']},{'title':'Services and Networking','weight':'20%','lessons':['services-dns','network-policy','ingress']}], 'cka':[{'title':'Cluster Architecture, Installation and Configuration','weight':'25%','lessons':['cluster-internals','kubeadm','availability','upgrades','etcd-recovery','extension-interfaces','admin-rbac','helm','kustomize','extensions']},{'title':'Workloads and Scheduling','weight':'15%','lessons':['scheduling','autoscaling','disruptions','rollouts','configuration','workload-choice']},{'title':'Services and Networking','weight':'20%','lessons':['cni-dataplane','coredns','gateway-api','network-policy','services-dns','ingress']},{'title':'Storage','weight':'10%','lessons':['csi-storage','storage']},{'title':'Troubleshooting','weight':'30%','lessons':['node-triage','control-plane-triage','network-triage','observability','cka-capstone']}], 'gcp':[]}
if (ROOT/'src/gcp-domains.json').exists():domains['gcp']=json.loads((ROOT/'src/gcp-domains.json').read_text())
sources=[{'title':'CNCF CKAD and CKA curricula','url':'https://github.com/cncf/curriculum','note':'Domain mapping, weights and detailed objectives; CC BY 4.0.'},{'title':'Kubernetes documentation','url':'https://kubernetes.io/docs/','note':'Concepts, tasks and API references. Each lesson links its relevant pages.'},{'title':'Kubernetes Basics tutorial','url':'https://kubernetes.io/docs/tutorials/kubernetes-basics/','note':'Public introductory teaching sequence.'},{'title':'Kubernetes the Hard Way — Kelsey Hightower','url':'https://github.com/kelseyhightower/kubernetes-the-hard-way','note':'Manual cluster-building reference; linked, not copied.'},{'title':'KodeKloud public CKAD course outline','url':'https://kodekloud.com/courses/certified-kubernetes-application-developer-ckad','note':'Public teaching-format reference; no paid course or exam material reproduced.'},{'title':'kind quick start','url':'https://kind.sigs.k8s.io/docs/user/quick-start/','note':'Local learning cluster setup.'},{'title':'Linux Foundation candidate FAQs and preparation rules','url':'https://docs.linuxfoundation.org/tc-docs/certification/faq-cka-ckad-cks','note':'Verify current rules and permitted resources before taking an exam.'},{'title':'Google Associate Cloud Engineer exam guide','url':'https://cloud.google.com/learn/certification/guides/cloud-engineer','note':'ACE objectives and preparation guidance.'},{'title':'Google Professional Cloud Architect standard exam guide','url':'https://services.google.com/fh/files/misc/professional_cloud_architect_exam_guide_english.pdf','note':'Current standard exam objectives, reviewed 2026-09-28; separate from the renewal guide.'},{'title':'Google Cloud Well-Architected Framework','url':'https://cloud.google.com/architecture/framework','note':'Operational, security, reliability, cost, performance and sustainability perspectives.'}]
validation=(ROOT/'src/validation.txt').read_text() if (ROOT/'src/validation.txt').exists() else 'Examples are original teaching fixtures. Execution verification is in progress; expected outcomes are not claimed as observed results. Policy, ingress, VM-administration and cloud exercises require their stated environments.'
data={'glossary':json.loads((ROOT/'src/glossary.json').read_text()),'deepDiagrams':json.loads((ROOT/'src/deep-diagrams.json').read_text()),'lessons':LESSONS,'labs':{str(p.relative_to(ROOT/'labs')):p.read_text() for p in sorted((ROOT/'labs').rglob('*')) if p.is_file()},'commands':commands,'domains':domains,'assessments':json.loads((ROOT/'src/assessments.json').read_text()),'sources':sources,'reviewed':'2026-09-28','validation':validation}
(ROOT/'content/course.json').write_text(json.dumps(data,ensure_ascii=False,indent=2))
js='const DATA='+json.dumps(data,ensure_ascii=False).replace('</','<\\/')+';\n'+(ROOT/'src/app.js').read_text()
css=(ROOT/'src/style.css').read_text()
mark=(ROOT.parent/'brand/techknowen-mark.svg').read_text().replace('id="title"','id="brand-title"').replace('id="desc"','id="brand-desc"').replace('aria-labelledby="title desc"','aria-labelledby="brand-title brand-desc"')
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Original TechKnowen Kubernetes and Google Cloud learning: foundations, CKAD, CKA, GKE, hands-on labs and visual explanations."><title>Kubernetes & Cloud · TechKnowen</title><link rel="canonical" href="https://chandra-79.github.io/tech-knowen-sdlc-field-guide/kubernetes/"><meta property="og:title" content="Kubernetes & Cloud · TechKnowen"><meta property="og:description" content="71 visual lessons from first containers to CKAD, CKA, Google Cloud ACE and PCA/GKE practice."><meta property="og:type" content="website"><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 32 32%22%3E%3Ccircle cx=%2216%22 cy=%2216%22 r=%2212%22 fill=%22%23087f79%22/%3E%3C/svg%3E"><style>'''+css+'''</style></head><body><a class="skip" href="#main">Skip to lesson</a><aside><a href="#/" class="brand"><span class="brand-mark">'''+mark+'''</span>TechKnowen<small>KUBERNETES & CLOUD</small></a><nav id="navigation" aria-label="Learning programme"></nav></aside><div class="shell"><header><button id="menu" aria-label="Toggle navigation" aria-expanded="false">☰</button><span class="header-title small">LEARN · BUILD · VERIFY</span><form id="search-form" role="search"><input id="search" type="search" aria-label="Search lessons and labs" placeholder="Find a concept, command or failure…"><button type="submit">Search</button></form><button id="theme" aria-label="Switch colour mode">◐</button></header><main id="main" tabindex="-1"></main><footer>TechKnowen · Original learning material · <a href="https://ajnacs.com/" target="_blank" rel="noopener noreferrer">ajnacs.com</a> · <a href="#/sources">Sources & scope</a></footer></div><script>'''+js+'''</script></body></html>'''
(ROOT/'index.html').write_text(html)
assert len({l['id'] for l in LESSONS})==len(LESSONS)
for l in LESSONS:
 assert len(l['nodes'])==3 and all(l[k] for k in ['summary','understand','deep','case','lab','verify','fault','answer','refs'])
 assert not l['code'].startswith('@lab:') or l['code'][5:] in data['labs']
print(json.dumps({'lessons':len(LESSONS),'tracks':{k:sum(l['track']==k for l in LESSONS) for k in ['foundation','ckad','cka','gcp']},'files':len(data['labs']),'bytes':len(html.encode())}))
